### ISSUE TITLE
[Q] [special characters wrongly formatted in group name]

### ISSUE THREAD

**Issue by emilemathieu** [wandb/wandb#1954]
Hello,

Weirdly in one of my project (but not the other one), the group name does not handle special characters well. After clicking on it I get redirected to a wrongly formatted url which is saying `No metrics logged yet.`
For instance: `Group: test_+experiment=rotmnist,aug=0.00,param=amortized` yields `https://wandb.ai/.../groups/test_%2Bexperiment%3Drotmnist%2Caug%3D0.00%2Cparam%3Damortized?workspace=user-emilem`.

Would this be specific to something I've done, or are special characters not allowed?

Best,
Emile

**Comment by ariG23498** [comment]
Hey @emilemathieu 
Thanks for the bug report. 

We have tried reproducing the issue and it turns out that there is a problem with special characters in the `group` parameter. With special characters in `group`, the dashboard does show the group of runs as shown below 👇 
![image](https://user-images.githubusercontent.com/36856589/111114909-ee4d7700-8589-11eb-9069-d3f6e22d490a.png)

But upon clicking on the group name, we see that the URL of the group messes up and redirects to another page (as has been reported by you) 👇 
![image](https://user-images.githubusercontent.com/36856589/111114959-fefded00-8589-11eb-9d86-42d417941ac0.png)

We will be tracking this internally. 😄

**Comment by emilemathieu** [comment]
Great! I believe that this issue is fairly new btw ~2 weeks, it worked well before.

**Comment by emilemathieu** [comment]
Would there be any update on this? :)
I'm happy to help!

**Comment by sydholl** [comment]
In the past year we've majorly reworked the SDK and UI for Weights & Biases and this issue should no longer be present. If this issue persists, please comment to reopen.
