### ISSUE TITLE
[CLI] os.symlink(abs_path, wandb_path) PermissionError: [Errno 1] Operation not permitted:

### ISSUE THREAD

**Issue by Wilann** [wandb/wandb#2801]
**Description**
Saving model via `wandb.save` not working

**Wandb features**
When trying to save my model with `wandb.save(save_model_path)` I'm getting error:
```
Traceback (most recent call last):
  File "CALF/src/main.py", line 370, in <module>
    main()
  File "CALF/src/main.py", line 256, in main
    wandb.save(save_model_path)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1270, in save
    os.symlink(abs_path, wandb_path)
PermissionError: [Errno 1] Operation not permitted: '/media/wilsonchan/Giratina/Projects/BadmintonAI/AceOne-BadmintonAI/CALF/models/2021-10-19_09-52-47_CALF_Simple.pth.tar' -> './CALF/wandb/r
un-20211019_095248-2ecqxesh/files/CALF/models/2021-10-19_09-52-47_CALF_Simple.pth.tar'
```

**How to reproduce**
N/A

**Environment**
- OS: Pop! OS 20_04
- Environment: Conda Env + Python scripts
- ython Version: 3.8.11

May be related to #2790?

**Comment by vanpelt** [comment]
The permission error is either being caused by cross link issues, or perhaps in this case it's actually caused by windows not allowing symlinks in your terminal session.  I think if you run your code in a terminal that's been opened [as an administrator](https://superuser.com/questions/1560049/open-windows-terminal-as-admin-with-winr) it should work.

**Comment by balloch** [comment]
> by cross link issues
What does this mean? this is causing trouble for me too
