### ISSUE TITLE
[CLI]: `WANDB_DIR` env. var. does not affect the location of the `artifacts/` directory

### ISSUE THREAD

**Issue by samuela** [wandb/wandb#3824]
I specifically set `WANDB_DIR` so that I can avoid downloading large files on expensive file storage, and instead place them onto cheaper local storage. Why then does the wandb client still download gigabytes of files into the `~/my/project/artifacts` directory? What environment variable do I set to affect where wandb stores these heavyweight files?

AFAIU I don't see any relevant variable in the [official docs](https://docs.wandb.ai/guides/track/advanced/environment-variables).

**Comment by samuela** [comment]
Also, what is the difference between `~/my/project/artifacts` and `~/.cache/wandb/artifacts`?

**Comment by vanpelt** [comment]
@samuela by default when you call .download on an artifacts it's writes that data to the current directory.  You can override what directory download writes to with the root argument of that method.

All artifact data is written through the cache.  You can change the location of the cache with the WANDB_CACHE_DIR environment variable.

**Comment by mesllo** [comment]
I am trying to set the WANDB_DIR environment variable to another location as I do not have enough space in my current directory, but it does not seem to make any difference. Is this related?

**Comment by vanpelt** [comment]
Hey @mesllo by default calling `.download` writes through the cache to the current working directory.  You change the destination of the downloaded files by specifying `root` in your call to download.  `artifact.download(root="/path/with/space")`

**Comment by mikkelkh** [comment]
@vanpelt `.download` allows specifying a `root` directory to store the artifact, but `.get` doesn't. So if I want to download and load the content of an artifact into a variable, it seems there is no way to avoid this to be stored inside `~/my/project/artifacts`?

**Comment by vanpelt** [comment]
Hey @mikkelkh for special objects like `wandb.Table` we need to stage the on the filesystem.  I haven't tested this but you should be able to do:

```python
cwd = os.getcwd()
os.chdir("/tmp")
foo = artifact.get("...")
foo.do_something()
os.chdir(cwd)
```

Can you tell me more about your specific usecase?

**Comment by mikkelkh** [comment]
That would probably work, yes. Currently, I've made a symbolic link that maps from `~/my/project/artifacts` to `/path/with/space`, which is somewhat of a similar hack, I guess.

My usecase is that I have a large dataset artifact that I'm synchronizing/downloading before every training. The dataset consists of images+labels and a `wandb.Table` (`table_dataset`) that visualizes the images, labels and annotations. 
For each run, I generate a (unique) train/val/test split as a `wandb.Table`, which I would like to merge with the dataset table.
Currently, I have a working version like this:

```
# Sync dataset
artifact_dataset = wandb.use_artifact("my_dataset:latest")
artifact_dataset.download(root="/path/with/space")
table_data = artifact_dataset.get("table_dataset")

# Generate split (e.g. from a pandas dataframe)
table_split = wandb.Table(dataframe=df_split)

# Merge tables and log
artifact_split = wandb.Artifact(name="my_dataset", type="splits")
table_merged = wandb.JoinedTable(table_data , table_split , "some_unique_id")
artifact_split.add(table_merged , "split")
wandb.log_artifact(artifact_split)
```

However, ideally, I would like `table_data = artifact_dataset.get("table_dataset")` to load the table directly from `/path/with/space`, since I've already downloaded it there. But as a second option, it would be nice to be able to specify `.get(root="/path/with/space")`, such that the table (including all its media images) isn't downloaded twice at different paths.

**Comment by rsanandres-wandb** [comment]
If you wish to use get to download an artifact into a particular directory, you can run the CLI command `wandb artifact get entity/src_project/my-artifact:v0 --root=<path/to/directory` (here our [docs for this command](https://docs.wandb.ai/ref/cli/wandb-artifact/wandb-artifact-get)). From there you will be able to use [download](https://docs.wandb.ai/ref/python/public-api/artifact#download) to gather the contents of the artifacts.

**Comment by chris-remedy** [comment]
Seems like this can be fixed by setting `os.environ[wandb.env.ARTIFACT_DIR]`? At least the version of this problem I had, that fixed.
