### ISSUE TITLE
Analyzing hyperparameters without actually performing sweep [Q]

### ISSUE THREAD

**Issue by urosjarc** [wandb/wandb#3906]
Hy, I’m in love with wandb, but I have a problem…

I have a simple question…

How can I analyze hyperparameters…As seen in this picture, without actually creating a sweep.

In my own code…

![68747470733a2f2f692e696d6775722e636f6d2f5455333451465a2e706e67](https://user-images.githubusercontent.com/8678755/177725197-17a0cb23-36b0-4f63-aa73-f50e631cdec2.png)

I’m preforming learning and for every model i’m sending config with hyperparams…

wandb.finish(quiet=True)
wandb.init(
entity=var.WANDB_ENTITY,
project=f’{var.version} | {var.INPUT_DATASET}',
dir=str(var.working_dir),
config=utils.keras.hyper_params(hp))

But in dashboard I dont see hyperparameters dashboard… And this makes me really sad !

This is my home dashboard for a project...
![unnamed](https://user-images.githubusercontent.com/8678755/177725365-9973425f-13f0-418b-adba-f06351a0b096.png)

And my table view of the project with all models config...
![unnamed (1)](https://user-images.githubusercontent.com/8678755/177725422-77da44d5-3610-48a1-b6d9-2b869e63137b.png)

**Comment by urosjarc** [comment]
Hy I have contact wandb support and they teach me how to create hyperparameter graphs without actually performing a sweep. In the project dashboard, I missed "Parameter Importance" and the "Parallel Coordinates" panels, by clicking on the "+ Add Panel" button in the dashboard. You guys should add those 2 graphs by default since it's really easy to miss those options in the project dashboard.

I would like to congratulate all your team for creating such a great product! You guys put a lot of care into it. And those little details are so refreshing.  Hats off!!! 👍 💯

**Comment by stephano41** [comment]
@MBakirWB Is it possible to create these panels (parallel coordinate and hyperparameter importance) from the client API instead of the App UI? As it is quite tedious when one runs multiple hyperparameter tuning experiments and have to select the config for these tables each time.

I get that you could probably mess around with Vega until you get the right colour and values with Vega, but is there an easier way to directly to the Vega JSON that a parallel coordinate graph generates so that we can learn from it to see what to use?

**Comment by xinbeiG** [comment]
Hi @MBakirWB,  when using `Add Pane` button in App UI to create `Parallel Coordinates` panel, is it possible to add multiple columns at one time? It's kind of tedious to add axes one by one manually.
