### ISSUE TITLE
[Q] What is diff.patch?

### ISSUE THREAD

**Issue by Waterkin** [wandb/wandb#3932]
Hi,
It takes up a lot of my storage, can I cancel these backups?

**Comment by vanpelt** [comment]
It's a unified diff of all un-commited changes in your git repository.  We generate this by default so that we can restore your working source directory to reproduce the run.  You can set the `WANDB_DISABLE_CODE` environment variable to true to prevent us saving your code, or you can disable it on the `/settings` page for your account or team.

**Comment by Waterkin** [comment]
> 

Thanks for your reply, Pelt.
After I disabled it, the diff.patch files still exists. Is there a way to choose all diff.patch and delete them?

**Comment by Waterkin** [comment]
It seems difficult to delete all diff.patch in my storage while they takes up 100GB.

**Comment by armanhar** [comment]
Hey @Waterkin, you can use the [Public API](https://docs.wandb.ai/guides/track/public-api-guide?q=public+#delete-all-files-with-a-given-extension-from-a-run) to delete all the diff patches in a project.
