### ISSUE TITLE
[Q] visualizing pairwise cosine similarity of embeddings

### ISSUE THREAD

**Issue by SN4KEBYTE** [wandb/wandb#4092]
Hello! I've recently started using W&B and I have a question: does W&B offer native tools to visualize pairwise cosine similarity? I want to get a picture like this one:
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/36272321/184406792-3e38f12e-c10c-460e-abef-60ba12fe9e8d.png">

For now, I'm using matplotlib for drawing such pictures and then log them like this:
```python
plt.imshow(similarity)
plt.colorbar()
wandb.log({'similarity': plt})
```

I found such thing as ```wandb.plots.HeatMap```, but it's marked as deprecated.

Thanks!

**Comment by fdsig** [comment]
Hey @SN4KEBYTE ,

Thanks for your question and the plot color bar sharing some really nice-looking plots. We do not currently support cosine similarity rendered as media in the UI, but you are correct that you could use heatmaps for this. Here is a [report](https://wandb.ai/lavanyashukla/vega-plots/reports/Log-ROC-PR-curves-and-Confusion-Matrices-with-W-B--Vmlldzo3NzQ3MQ) and here is a  [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1959tqn82yyjanOOZmCm4tDUI_iWSFe-W) showing some examples of logging custom plots including heatmaps.

Since the heat maps you have shown are rendered as images of 2d arrays you could also log them as [media](https://docs.wandb.ai/guides/track/log/media)  `wandb.Image()` and or include these in a WandB [weave table](https://docs.wandb.ai/ref/app/features/panels/weave)  if you wanted to store data alongside them in a row by row fashion. 

Here is a short code snippet of how this might look:

```python 
tbl = wandb.Table(
    columns=2, rows=10, data=df)
tbl.add_column(name='image',data=images)
tbl.add_column(name='data',data=h_map)
```

Hope this helps!

**Comment by fdsig** [comment]
Hi @SN4KEBYTE , Let us know if you need any further help here otherwise I will go ahead and close this off.
