### ISSUE TITLE
[Q] How to log the model every n steps and the best model with SB3

### ISSUE THREAD

**Issue by JoseBarreiros-TRI** [wandb/wandb#4152]
Hi, 
I would like to log the model (.zip) continuously and query the best model at the end of the training. I am using the WandbCallback for SB3.

**Comment by nate-wandb** [comment]
Hi @JoseBarreiros-TRI,
Would it work for you to query the run with the public API to find out if the current model is better than the previous best model and if so, save it to a different file in the UI during the training? 

Also, are you trying to query to find the best model in the UI or from the API? I may be able to come up with a solution since it sounds like you've already done your training and the above solution would require doing this at the time of training.

Thank you,
Nate

**Comment by nate-wandb** [comment]
@JoseBarreiros-TRI I see, thank you for the clarification. I would upload the model directory as an Artifact in this circumstance. 

So for instance:
```
best_model_path = 'models/best/'
eval_callback = EvalCallback(best_model_save_path=best_model_path)
artifact = wandb.Artifact(name='best-model', type='model')
artifact.add_dir(best_model_path)
wandb.log_artifact(artifact)
```

Let me know if this is closer to what you are looking for.

Thank you,
Nate

**Comment by nate-wandb** [comment]
Hi @JoseBarreiros-TRI,
I wanted to follow up and see if that worked as a solution for you?

Thank you,
Nate
