### ISSUE TITLE
[Q] Visualizing hyperparamter tuning with existing custom runs

### ISSUE THREAD

**Issue by meghbhalerao** [wandb/wandb#4228]
Hi, is there a way to visualize hyper parameter tuning plots such as the parallel coordinated plots (and all the other stuff which can be obtained from the wandb sweep agent) by something like adding my own custom runs which I can control easily from my CLI and visualizing them, rather than having wandb run jobs on my local system which is quite cumbersome I think.
Please let me know if anything is unclear in my question.

**Comment by lesliewandb** [comment]
Hi @meghbhalerao, you can put a parallel coordinate plot into your workspace by clicking on '+ Add Panel' on the top right of your workspace. However, for the second part of adding your own custom runs, are you wanting to add data to wandb via UI instead of through our API? Because at this moment we don't have this capability. Let me know if I'm misunderstanding what you're asking for

**Comment by lesliewandb** [comment]
Hi again @meghbhalerao, was this able to help you?

**Comment by meghbhalerao** [comment]
Hi @lesliewandb, yes I understood. Closing this issue. Thanks again for your help!
