### ISSUE TITLE
[Q] Why doesn't `wandb sync --include-offline` upload any metrics?

### ISSUE THREAD

**Issue by ndrwnaguib** [wandb/wandb#4453]
I am running wandb in offline mode on SLURM; the runs have completed, when I try to sync, only the sweeps ids are synced, but neither the runs nor the metrics show up. The reporting works fine in online mode.

I am syncing the runs with `wandb sync` (also tried `wandb sync --include-offline`). But, no metrics are uploaded, I don't even know where are they stored on disk so that I could parse them manually. 

The following error occurs when trying to sync a specific run

```
Syncing: https://wandb.ai/ndrwnaguib/ai4l/runs/fqtlxdz1 ...Exception in thread Thread-1:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ndrw/.local/lib/python3.8/site-packages/wandb/sync/sync.py", line 267, in run
    sm.send(pb)
  File "/home/ndrw/.local/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 233, in send
    assert record_type
AssertionError
```

Any thoughts what could have gone wrong? Thanks.

**Comment by ramit-wandb** [comment]
Hi @ndrwnaguib,

That's odd - Could you share the `debug.log` and `debug-internal.log` files associated to an affected run? They should be present on your machine in the `wandb` folder relative to your working directory and should contain some more information about these runs so that we can dig in deeper.

Running `wandb sync --sync-all --include-synced` should also generate a log, it would be great if I could have a look at that as well. I'll have to dig into this a little more before I can give you a concrete answer for what might be happening here.

**Comment by ramit-wandb** [comment]
​Hi @ndrwnaguib, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​
