### ISSUE TITLE
[Feature]: Adding created timestamp to the run summary / config

### ISSUE THREAD

**Issue by backpropper** [wandb/wandb#4472]
### Description

Just like there is '_timestamp' to denote the current timestamp, it would be great if there is a key 'created_timestamp' that denotes the time as which the run was created. 

### Suggested Solution

I see this in the UI but not in the API. I'm currently getting this from the history and extracting the timestamp from the first entry.

**Comment by fdsig** [comment]
Hey @backpropper ,

Thanks so much for asking a question about the important subject of how time is recorded.  You are correct that the _timestamp attribute of run history is incremental step time.

If you are in the same runtime and want the runtime of a run then it would be possible to get the start time as follows:
 
 ```python
 run = wandb.init(entity='demonstrations',project='time')
run.start_time
```
which will yield :  `1667991415.867529`

If you wanted to access this via  a run's history using our public API you could log then log this:

with:

```python
 run.log('start_time':run.start_time)
 ```
 
If you are looking to receive already finished runs in separate runtime. In order to draw down the run start time of a particular run programmatically and return this inside a new runtime you would need to do the following:

```python

import wandb
import yaml
from pathlib import Path

api = wandb.Api()
# paste in run hash 
RUN_ID = '2qv9fzs5'
# put in project name
PROJECT = 'your_project'
# put in team/username (wandb entity) 
ENTITY = 'your_team'
# directory where you want config
DIR = 'save_dir'
# call public api using above
run_call = api.run(f'{ENTITY}/{PROJECT}/runs/{RUN_ID}')
# iterate through called run files
for fid in run_call.files():
  # conditionally download the config
  if fid.name == 'config.yaml':
    fid.download(DIR,replace=True)
# create pathlib path object
path = Path(f'{DIR}/config.yaml')
# read downloaded .yaml  as python dict from yaml and target start time value
yaml.safe_load(path.read_text())['_wandb']['value']['start_time']
```
which will yield:   `1667991433.541734`

Let me know if the above would be suitable for your use case and have made the code slightly more verbose than necessary for readability.

**Comment by backpropper** [comment]
Thanks for the detailed answer. I see that start_time is stored the config.yaml

But after searching over my runs, I realized that many of them only save two files (`code/train.py` and `wandb-metadata.json`) and the other files such as `config.yaml`, `wandb-summary.json`, etc. Is there a bug here?

**Comment by fdsig** [comment]
Hey @backpropper , 

Thanks for messaging back here. Each run should have its own individual config. A quick way to see what files are visible for a particular run would be to view your run file page via your workspace in our UI of a run where you are not seeing config that you want.  

This can be done as follows: 
>>1. Navigate to individual run:
>> ![to_run_in_worksapce_2022-11-14 at 10 30 47](https://user-images.githubusercontent.com/65113682/201638577-92f59c25-d634-4ae0-87ff-69bd4491e547.png)
>> 2. Then go to the files tab:
>> ![to_run_files-11-14 at 10 17 54](https://user-images.githubusercontent.com/65113682/201638699-8bf9127f-ac8b-416b-83f6-b46852017416.png)


If you are accessing these via our Public API methods in the WandB SDK then I wonder if you would be able to share a code snipped of how you are querying/ iterating over runs in a project. 

Look forward to hearing back from you. 

Frida

**Comment by fdsig** [comment]
Hey @backpropper ,

I wanted to check in and see if you still needed help here or if I should go ahead and close this off for you.

Look forward to hearing back from you.

~/ Frida

**Comment by backpropper** [comment]
Apologies for the late response. I realized that the issue was from my end as the jobs got crashed before the files could save.

**Comment by fdsig** [comment]
Hey @backpropper,

No problem at all and happy that you are back on track 😊 for your experiment tracking, please do reach out if you need any further support.

Have a great weekend. 


~/Frida
