### ISSUE TITLE
[App]: Values are OMITED when exporting to csv!!!

### ISSUE THREAD

**Issue by Leonezz** [wandb/wandb#4501]
### Current Behavior

When I using the csv export function to export my sweep data, some columns of data are just empty, and I can see them on the web table app. In the downloaded csv file, there is just the column names, not the data, that is a very bad situation for a data logging tool.

### Expected Behavior

All logged data should be in the downloaded csv file.

### Steps To Reproduce

1. Go to table view of a sweep.
2. click the export button and chose the csv export function.
3. download the file and check it out.

### Screenshots

In the web table app, the values are just there:
![image](https://user-images.githubusercontent.com/33564074/202676076-44c63fa4-d98c-4443-97c1-7e19bab5eceb.png)

In the export view and downloaded file:
![image](https://user-images.githubusercontent.com/33564074/202676270-7e64d5c4-1aaa-450f-b82e-359dc78a6c0c.png)

### Environment

OS: Window 11

Browsers: Microsoft Edge

Version:

### Additional Context

Very bad situation, I can't image what happend.

**Comment by AaronSpieler** [comment]
I have the same issue, EXTREMELY annoying. Essentially data is locked in. Havent tried API yet.

OS:  Ventura, Borwoser: Brave 1.45.127

**Comment by thanos-wandb** [comment]
Hi @Leonezz @AaronSpieler thanks so much for reporting this. We are currently investigating this issue. In the meantime, may I please ask to see if API works for you? Also, how are these missing column data logged, do they come from external arguments in your python scripts?

**Comment by AaronSpieler** [comment]
Hi @thanos-wandb. The values are there if I download using the API.
They are hyperparameters of my model that I log.
They are logged once in the beginning of the trains script using a nested dict.

I also noticed that when doing the smart column select (the magic wand thingy), it doesnt recognise columns anymore that vary wrt parameters, except for non nested numeric values.

Also I noticed, the problem occurs now for all my projects. I.e. the smart colum select doesnt see those columns and that the parameters vary. Also the csv preview shows empty columns.

Just going to the table view and looking at the parameters works fine though.

**Comment by thanos-wandb** [comment]
Hi @AaronSpieler thanks so much for the update, this has been reproduced on our end and I have created an internal ticket for our engineering team. I will keep you posted here on any updates. In the meantime, you could also singly group the runs you're interested at, this seem to do the trick to download the `config` column data as well. For instance if you have unique run names then you could `Group` by `Name` so that it's only a single entry in each group. Please let me know if that works for you.

**Comment by Leonezz** [comment]
Hi, sorry for the late reply.
The API download works for me. The missing columns I noticed and are important to me are the hyperparameters I setted in the sweep configs.

**Comment by thanos-wandb** [comment]
@AaronSpieler indeed the issue is related to `config` values and the parameter importance panel, and the magic wand tool for the column filtering you mentioned before are affected too. 

@Leonezz thanks for the update, another way to get the missing columns for now would be to import a Weave panel in your project's Workspace with the expression: `runs.config` then you can export this table as CSV. 

I will keep you updated once this issue is fixed.

**Comment by thanos-wandb** [comment]
Hi @Leonezz @AaronSpieler our engineering team reverted a PR in our public cloud instance that was causing this issue you were experiencing earlier, and it should be now resolved for you. Apologies for any inconvenience this may caused. Please let me know if you still experience this issue.

For future reference: the issue is in the W&B local/server v0.23.0, and we will be soon releasing a patch.

**Comment by Leonezz** [comment]
Thanks for your work, the reverting seems solved the issue for me, closing this issue.

**Comment by avani17101** [comment]
I am also facing this issue, only top 10k rows are being downloaded instead of entire 50k rows.

How to work around this?
