### ISSUE TITLE
Still upload data when I turn on offline mode[Q]

### ISSUE THREAD

**Issue by ShaohanTian** [wandb/wandb#4524]
This is my code, I don't know why my log will still upload, although I have turn  on 'offline' mode? (wandb version==0.13.4)
```python
import wandb
import os
import signal
import argparse
import wandb
import time
os.environ["WANDB_MODE"] = "offline"

sweep_configuration = {
    "project": 'hello1',
    "name": "my-awesome-sweep",
    'metric': {
        'goal': 'minimize', 
        'name': 'accuracy'
	},
    "method": "grid",
    "parameters": {
        "a": {
            "values": [1, 2, 3, 4]
        }
    }
}

def my_train_func():
    # read the current value of parameter "a" from wandb.config
    wandb.init(mode='offline', force='False')
    a = wandb.config.a

    wandb.log({"a": a, "accuracy": a + 1})

sweep_id = wandb.sweep(sweep_configuration)

# run the sweep
wandb.agent(sweep_id, function=my_train_func, count=2)
```

**Comment by thanos-wandb** [comment]
Hi @ShaohanTian thank you for your question! The `offline` mode refers to the `wandb.run` instances, where all data will be stored locally (and can be `sync`ed later on to the W&B server). 

For the sweeps though, there is no offline method, as the SDK/CLI needs to communicate with the Sweeps server to generate a sweep id for the parsed `config` dictionary, so that the agents will know which hyperparameters to use. Please find a high-level overview of the sweep process in the attached screenshot, I hope this helps.

![1_Sweeps%20High%20Level%20Overview](https://user-images.githubusercontent.com/108423944/203615197-058647ef-0ea8-4aee-aa4c-648545ce0629.svg)

May I please ask what's the use case here, and if you wanted to have everything offline? In that case, you might want to use a s[elf-hosted](https://docs.wandb.ai/guides/self-hosted) W&B instance.

**Comment by ShaohanTian** [comment]
I see, thank you

**Comment by thanos-wandb** [comment]
Hi @ShaohanTian you're welcome, glad this answers your question. Just to clarify here that initializing standalone runs (which are not part of sweep) that shouldn't upload anything unless `sync`ing them to the server. I am closing this ticket for now, but please feel free to re-open it if you have further questions about this.
