### ISSUE TITLE
[Feature]: Concatenate output (stdout/stderr) when resuming experiment

### ISSUE THREAD

**Issue by henrik-schopmans** [wandb/wandb#4727]
### Description

When resuming an experiment (with resume=True), currently the old output.log gets overwritten with the new output.
When I look at the log in the web ui, the old output is still displayed. However, if I download the log in the top right corner, I get the new log file. In "Files" on the web ui, there is also only the new output.log.

### Suggested Solution

When resuming a run, the content of the new output.log should be concatenated to the old log.

**Comment by MBakirWB** [comment]
Hi @henrik-schopmans, thank you for writing in. I was able to reproduce this behavior on my end and will be flagging for eng to review.

**Comment by LeSphax** [comment]
Hello ! 

I think I'm running into the same issue, when resuming a run the stdout logs get erased and only the logs for the resumed part are available.

We are using the resume feature to interstich training and eval steps for our model right now so having the whole log in one place would be helpful

Is it still not possible to do?

**Comment by kptkin** [comment]
@LeSphax @henrik-schopmans , sorry, this is a weird behavior that we should fix! 
The reason this is happening this way is because the client is responsible for generating the output file. When resuming, the client doesn't download the entire data (obviously) it just gets the relevant resume offsets from the server and starts streaming the data. That's why the logs in the UI look correct, however it does write the new output file causes it to be overwritten. This is indeed a sub optimal behavior and we are going to look into a fix here. (adding it to our milestones for scoping)
