### ISSUE TITLE
[App]: Deleting all versions of Artifact leave "Empty" Artifact in app

### ISSUE THREAD

**Issue by timsetsfire** [wandb/wandb#4816]
### Current Behavior

when using the wandb api to delete ALL versions of an artifact will leave an empty artifact in the UI.  

### Expected Behavior

The desired behavior is to hide or remove the empty artifact.  

### Steps To Reproduce

1. pick an artifact with several version 
2. query the artifacts via api
3. delete the artifacts.  
4. return to the UI and you will see an Artifact with no versions

### Environment

OS:

Browsers:

Version:

### Additional Context

existing WB12014

**Comment by ArtsiomWB** [comment]
Hi @timsetsfire! Thank you for writing in. Could you send me an example and a code snippet of you reproducing this on your side if possible? Also I am assuming this happens on public cloud?

**Comment by ArtsiomWB** [comment]
Hi @timsetsfire , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by mmlynarik** [comment]
Hi, the problem is also reproducible from app GUI. When you delete a run, and agree to delete all artifacts, it will delete all versions, but the artifact object itself is left undeleted with no versions. Does this behaviour make sense?

![image](https://github.com/wandb/wandb/assets/44208384/b8b46e3e-25bd-4ec9-b6a4-eae24ed47624)
