### ISSUE TITLE
[Q] Have random names become less random?

### ISSUE THREAD

**Issue by jonasreiher** [wandb/wandb#4881]
I feel like the number of possible first and second words for random run names has significantly decreased some time in the last months.

These are 15 runs in a new project from yesterday and today. We get multiple repetitions, 3x 'auspicious', 3x 'snake', 2x 'lambent', even 2x 'auspicious snake':
<img width="215" alt="image" src="https://user-images.githubusercontent.com/58821240/216066258-c3479336-65a7-4a7f-8e2a-160a9a323dca.png">

Compare this to 15 runs from a project a few months ago. There I can only find one repetition, 'charmed', even when looking at twice or thrice this number of runs:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/58821240/216068071-47ef4686-1b7a-41bc-97f4-4ad58ec995b8.png">

Am I just unlucky or did something change here?

**Comment by ArtsiomWB** [comment]
Hi @jonasreiher! This is a very interesting case. I went over all of our prs and commits and in general, there has been no change to the naming of runs. This suggests that you are being incredibly unlucky. Since the way we name runs completely randomly, this is definitely a possibility. 

If this keeps on happening continuously, please let us know and we'll contact our engineering team :)

**Comment by jonasreiher** [comment]
Alright, thank you for investigating! I will come back to you if this persists.
