### ISSUE TITLE
[Q]How to have multiple wandb.log() in same run?

### ISSUE THREAD

**Issue by DishantMewada** [wandb/wandb#5106]
I am trying to use multiple wandb.log() statements in my jupyter notebook. I kept 'id' the same so it will be added in the same run but the later wandb.log() is not reflecting. 

For example,
```
import wandb

id = wandb.util.generate_id()

print(id)

wandb.init(id = id, project="testing", name="faster_rcnn_r50_fpn_1x_coco", tags = "object_detection")

for i in range(10):

    wandb.log(

    {'acc': (i*0.1)**2, 'epoch': i, 'batch': i+5})

wandb.init(id = id, project="testing", name="faster_rcnn_r50_fpn_1x_coco", tags = "object_detection")

for i in range(10):

    wandb.log(

    {'acc1': (i*0.1)**2, 'epoch1': i, 'batch1': i+5})

wandb.finish()
```

This code only generates graph for acc, epoch, batch and the later log is not generating graphs.

Thank you.

**Comment by DishantMewada** [comment]
Using 

`wandb.init(id = id, project="testing", name="faster_rcnn_r50_fpn_1x_coco", tags = "object_detection", reinit = True)`

also doesn't work.

**Comment by DishantMewada** [comment]
Using
```
...
wandb.init(id = id, project="testing", name="faster_rcnn_r50_fpn_1x_coco", tags = "object_detection", resume = "Allow")
...
wandb.init(id = id, project="testing", name="faster_rcnn_r50_fpn_1x_coco", tags = "object_detection", resume = "Must")
...
```

It does work, but the step (x-axis) for the second wandb.log() starts where the previous wandb.log() left off.

**Comment by MBakirWB** [comment]
Hi @DishantMewada, please see [this doc](https://docs.wandb.ai/ref/python/log) on the intended use of wandb.log() within an experiment run

Wandb requires metrics to be plotted against one another to be logged at the same Step - that is how we keep your metrics synchronized. Wandb keeps track of a global step, which by default **increments** with each call to wandb.log, so logging related metrics together is encouraged.We recommend you bundle your metrics into the same log() call. If your code looks like this:

```
wandb.log({"Precision" : precision})
wandb.log({"Recall" : recall})
```
It would be better to log it as:
```
wandb.log({
    "Precision" : precision,
    "Recall" : recall
})

```
Alternatively, you can manually control the step parameter and synchronize your metrics in your own code:

```
wandb.log({"Precision" : precision}, step = step)
wandb.log({"Recall" : recall}, step = step)
```

If the value of step is the same in **both the calls to log(),** your metrics will be **logged under the same step** and be sampled together. Please note that **step must be monotonically** increasing in each call, otherwise the step value is **ignored** during your call to log().

**Comment by DishantMewada** [comment]
Thank you for the response. 

It would be great if there is some 'reset = True' option which resets the step. I am doing some analysis after the model is trained in mmdetection. It will take a long time for me to understand the entire code and put the wandb.log inside it wherever it is getting called so that the log only gets called once to make the step consistent.

As a workaround, I am using 'group' in my wandb.init() which puts run in different groups so that in the future same group experiments are easily compared.

**Comment by MBakirWB** [comment]
Hi @DishantMewada , thank you for the update and filing the feature request. I'll mark this resolved

**Comment by JiaxiangHuang** [comment]
`##=======================================================option 1

import wandb

wandb.init(project="log-example")
for i in range(10):
    wandb.log(
    {'acc': (i*0.1)**2,
     'epoch': i,
     'batch': i+5})


# define our custom x axis metric
wandb.define_metric("train/step")
# set all other train/ metrics to use this step
wandb.define_metric("train/*", step_metric="train/step")

for i in range(10):
    wandb.log(
    {"train/step":  i ,
     'train/acc1': (i*0.1)**2,
     'train/epoch1': i,
     'train/batch1': i+5})

wandb.finish()

##=======================================================option 2
import wandb

wandb.init(project="log-example")
for i in range(10):
    wandb.log(
    {'acc': (i*0.1)**2,
     'epoch': i,
     'batch': i+5})


# define our custom x axis metric
wandb.define_metric("mystep")
# set all other train/ metrics to use this step
wandb.define_metric("acc1", step_metric="mystep")
wandb.define_metric("epoch1", step_metric="mystep")
wandb.define_metric("batch1", step_metric="mystep")

for i in range(10):
    wandb.log(
    {"mystep":  i ,
     'acc1': (i*0.1)**2,
     'epoch1': i,
     'batch1': i+5})

wandb.finish()`
