### ISSUE TITLE
[CLI]: Wrong export data

### ISSUE THREAD

**Issue by gau-nernst** [wandb/wandb#5219]
### Describe the bug

When using the Python library to retrieve logged data, the data is **different** from the web UI's. Moreover, re-running data retrieval gives me **different** data, making me believe that the retrieved data is wrong.

```python
api = wandb.Api()
runs = api.runs("gau-nernst/heco", filters={"config.log_name": "baseline"})

runs[4].history()["loss"].head()
```

Re-running the above code several times

```
0    1.401042
1    0.859214
2    1.397540
3    0.860183
4    1.394031
Name: loss, dtype: float64

0    1.401042
1    0.858861
2    0.860320
3    1.396206
4    0.859123
Name: loss, dtype: float64

0    0.858821
1    0.859132
2    1.397540
3    0.859255
4    0.859463
Name: loss, dtype: float64
```

CSV export from Web UI

![image](https://user-images.githubusercontent.com/26946864/227100995-d7abeb83-6ccb-420d-99e7-4560876b2c55.png)

For some reasons, the values randomly become 0.85xxxx. This is a very serious bug.

### Environment

WandB version: 0.14.0

OS:  Ubuntu 18.04.6 LTS

Python version: 3.10.4

Versions of relevant libraries: protobuf==3.20.3

### Additional Context

My project is currently private. I'm not sure if Wandb employees can still access my project's data. If needed, I will make it public so that the bug can be re-produced.

**Comment by thanos-wandb** [comment]
Hi @gau-nernst thanks for writing in! Currently we will randomly subsample the data points rendered in W&B App, and also when [retrieved from the API](https://docs.wandb.ai/guides/track/public-api-guide#sampling) using the `history` method. In order to get the unsampled metrics you will need to use the `scan_history` method instead ([docs reference here](https://docs.wandb.ai/ref/python/public-api/run#scan_history)). Could you please try to adjust your example as follows:

```
api = wandb.Api()
runs = api.runs("gau-nernst/heco", filters={"config.log_name": "baseline"})

history = runs[4].scan_history(keys=["loss"])
display([row["loss"] for row in history])
```

Would this work for you?

**Comment by gau-nernst** [comment]
@thanos-wandb Thank you, `.scan_history()` works correctly now. For better user experience, would it be possible to make it more explicit that `.history()` samples the data? e.g. Raise a warning. Also, I see that `.history()` returns values not in chronological order. I feel like that can be quite confusing and make interfacing with wandb API more error-prone.

**Comment by thanos-wandb** [comment]
Hi @gau-nernst glad to hear this worked for you and thank you for the feedback! We do mention that these are sampled metrics in the `history` [API documentation](https://docs.wandb.ai/ref/python/public-api/run#history) but I will take a note of this so that the user is prompted about this behavior from the Python script too. May I please ask though regarding the issue you mentioned about the chronological order, do you refer to the `steps` being randomly selected, are these not always in increasing order for you? do you provide any arguments in `history` method?

**Comment by gau-nernst** [comment]
Hi @thanos-wandb, thank you for your reply. Yes, the randomly sampled "steps" are not in increasing order.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/26946864/229389756-74d67382-e3c3-4673-806d-874fc4420d92.png">

**Comment by thanos-wandb** [comment]
Hi @gau-nernst thanks for the additional information, this shouldn't happen for you, could you please upgrade to our most recent wandb client/SDK version (v0.14.2) and try again the following code snippet? 

```
for i, row in runs[4].history().iterrows():
  print(row['_step'], row['step'], row['mp/0'])
```

Any chance you've resumed to this run? or was it an offline run that was later synced?

**Comment by gau-nernst** [comment]
Hi @thanos-wandb,

I have updated to the latest v0.14.2 client. The problem is still there

![image](https://user-images.githubusercontent.com/26946864/231207447-d501e69d-bbe4-4fee-b8fe-eec602809d06.png)

Note that key `'step'` does not exist, only `'_step'` exists.

I didn't resume the run, nor ran it offline and synced later. But I was running multiple runs in parallel on the same machine (separate processes).

Also, this "bug" kinda deserves an issue on its own, since it's different from the original problem raised in this issue thread.

**Comment by thanos-wandb** [comment]
Hi @gau-nernst I agree this will need further debugging and information (eg which wandb client version logged this run), and also the original issue here has been resolved. Please free to create a new thread and we will be happy to assist you further with this bug. Thanks!
