### ISSUE TITLE
Log to closed run [Q]

### ISSUE THREAD

**Issue by MarMichaj** [wandb/wandb#5248]
Hi there,
I am new to the framework and could not find an answer to my fairly basic question so far:

Is there a possibility to log values to an already finished run? My use case is, that the training of a model was performed properly, but I had a bug in the test error evaluation at the end. Since I already have the training data, it would be nice if I could just manually log the test results to the already finished run.

**Comment by gsaltintas** [comment]
Hello,
You can indeed resume an existing run and log new values to it. Just make sure to pass the correct parameters to `wanbd.init`
```python
wandb.init(resume=True, project=PROJECT, id=RUN_ID)
```

**Comment by nate-wandb** [comment]
Thanks @gsaltintas for the answer! One small thing I wanted to note is that I would use `resume="must"` because `resume=True` will resume the most recent run from that machine which may not be the same run as the `run_id` you are passing as well. 

@MarMichaj does this seem like it would solve your use case? Also, there is more detailed information on the resume behavior in the [docs](https://docs.wandb.ai/ref/python/init) for `wandb.init` which may help clarify some.

**Comment by MarMichaj** [comment]
Thanks @gsaltintas and @nate-wandb, that solves my problems! Maybe it's also interesting to note, that if the ```id``` parameter was not passed to ```wandb.init()```, it can be found subsequently in the url of the run, which has the form: ```wandb.ai/team/project_name/runs/RUN_ID/...```

**Comment by nate-wandb** [comment]
Correct, and it is also an attribute of the run object `run.id`. Glad this answers your question!
