### ISSUE TITLE
[Q] How to get rid of the `ResourceWarning` warning?

### ISSUE THREAD

**Issue by yzhangcs** [wandb/wandb#5258]
Hi, thank you for providing such an excellent project to conveniently log my experiments.
However, I have encountered an issue. I found that once I installed wandb (even not import it yet), my running exps will raise many many warnings like this 
> tempfile.py:860: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpp1tj0s33wandb-media'>

which are quite bothersome.
I 've tried various solutions like directly suppressing warnings, but none of them works.
I was wondering if you could provide me with any assistance or ideas on how to resolve this issue?
Thanks!

**Comment by rsanandres-wandb** [comment]
Hello @yzhangcs!

The warning is not coming from our SDK - We don't have any files called `tmpfile.py` and we do not throw any `ResourceWarnings` directly. However, since the tmpfile is a wandb-media folder, it does mean that there has been previously logged `wandb.Image` or `wandb.Video` objects are being flushed (which is intended since they are tmpfiles).

**Comment by hauntsaninja** [comment]
@rsanandres-wandb the issue is in the way wandb uses the `tempfile` library (which is part of the Python standard library)

For example, you're creating a temporary directory at import time https://github.com/wandb/wandb/blob/6289d69a5ffb31738427f33e56b8e33d89ac467e/wandb/data_types.py#L82 . When do you expect this to be deleted? If not, you should specify `delete=False` or use `tempfile.mkdtemp()`. It's also generally a bad idea to create file system state at import time, consider deferring this, wandb import time is already terrible (although I've made it better in https://github.com/wandb/wandb/pull/5899 and https://github.com/wandb/wandb/pull/6032)

**Comment by hauntsaninja** [comment]
> Please let us know if we can be of further assistance 

@rsanandres-wandb just tagging again since you asked above if you could be of assistance :-)

**Comment by andrey-klochkov-liftoff** [comment]
Apparently wandb SDK creates a number of temporary directories when it's imported, and it never does a clean up. Here's a workaround to get rid of the warnings.

```
import wandb
from wandb import data_types
from wandb.sdk.data_types._private import MEDIA_TMP
from wandb.sdk.internal import file_pusher
from wandb.sync import sync

...

    tempdirs = [
        wandb.Artifact._TMP_DIR,
        file_pusher.TMP_DIR,
        data_types.MEDIA_TMP,
        MEDIA_TMP,
        sync.TMPDIR,
    ]
    for d in tempdirs:
        d.cleanup()
```
