### ISSUE TITLE
[App]: Strange `__MIN` & `__MAX` in csv exported from the web

### ISSUE THREAD

**Issue by fyqqyf** [wandb/wandb#5349]
### Current Behavior

I have the same problem as https://github.com/wandb/wandb/issues/5222#issue-1637710551.

### Expected Behavior

Only one column from the plot.
<img width="361" alt="image" src="https://user-images.githubusercontent.com/48092144/232418684-9b3d426d-4007-4715-951d-fdf954cd35d1.png">

### Screenshots

There are three strange columns (the last two are `__MIN` & `__MAX`):
<img width="942" alt="image" src="https://user-images.githubusercontent.com/48092144/232419288-a670a47f-0bb7-4f45-a4d3-722f2ddb64b3.png">

### Environment

OS:

Browsers:

Version:

### Additional Context

Thanks!

**Comment by ArtsiomWB** [comment]
Hi @fyqqyf! In the first post, you are expecting all 3 columns to be different right?

**Comment by ArtsiomWB** [comment]
I can definitely submit a feature request for you for the first point where it downloads 3 of the same columns. Technically, I wouldn't say that the max and min columns are wrong, but they are pointless if only a single graph is present. 

I'll look around for the second issue. It does seem like when you download the CSV it puts the graphs into all of their averages instead of downloading the graphs separately.

**Comment by ArtsiomWB** [comment]
No problem! You could potentially try using the wandb API, and then download a run and then try pulling out the necessary metrics from it that way. 

```
import wandb
api = wandb.Api()
runs = api.runs('<entity>/<project name>')
print(runs)
for run in runs:
  print(run.id)
for run in runs:
    history = run.scan_history()
    losses = [row for row in history]
    print(losses)
 ```
 
 The script above can get you all of the runs from your project and retrieve the data from those runs. 

Your feature request has been submitted.
