### ISSUE TITLE
[App]: Logging same Artifact multiple times is ignored

### ISSUE THREAD

**Issue by mimxrt** [wandb/wandb#5359]
### Current Behavior

Wandb does not allow (?) logging the same artifact multiple times. This would make sense for files that are shared for all runs in a sweep. Following MWE showcases this issue:

```python
import wandb
import pathlib
import numpy as np

csv_data = np.random.rand(3, 20)
csv_fn = pathlib.Path(__file__).parent / "some_data.csv"
np.savetxt(csv_fn, csv_data, header="C1,C2,C3")
a = wandb.Artifact("some_data", "csv", "Some data that all runs of this sweep share.")
a.add_file(csv_fn.as_posix(), name=csv_fn.name)


def func():
    wandb.init()

    # log artifact that is shared by all runs for this sweep
    wandb.log_artifact(a).wait()

    o = np.random.random()
    wandb.log({"error": o})

    wandb.finish()


wandb.login(
    key="",
    host="",
    relogin=True,
)

SWEEP_CONFIG = {
    "method": "random",
    "name": "my_config",
    "metric": {"goal": "minimize", "name": "error"},
    "parameters": {
        "param1": {"values": [8, 16, 32]},
    },
}

sweep_id = wandb.sweep(sweep=SWEEP_CONFIG, project="artifact")
agent = wandb.agent(
    sweep_id=sweep_id,
    function=func,
    project="artifact",
    count=5,
)
```
Only the first run shows the artifact in the web interface, all others don't have any artifacts.

### Expected Behavior

Wandb should show the logged file/artifact in all runs of the sweep.

### Steps To Reproduce

See MWE above.

### Environment

OS: Windows 11

Browsers: Microsoft Edge

Version: **W&B Local 0.31.1**

**Comment by nate-wandb** [comment]
Hi @mimxrt, this is expected behavior. When uploading an Artifact, the sdk will check the hash of the Artifact against the most recent version of the Artifact with the same name. If the two hashes are identical, the Artifact is not uploaded because a new version is not needed.

Could you explain the use case for uploading the same Artifact multiple times? You could give the Artifacts new names which would cause them to upload but I think if I understood the use case a little more I might be able to help with your end goal for this. 

Thank you,
Nate

**Comment by nate-wandb** [comment]
Hi @mimxrt, are the sweep runs creating the data or are they consuming it? It sounds like the latter which in that case I would upload the Artifact once and then all of your sweeps runs can consume the Artifact by using the guide [here](https://docs.wandb.ai/guides/artifacts/download-and-use-an-artifact). This will still attach the Artifact to the runs as an "input" Artifact, rather than "Output" in the data lineage. 

Let me know if I'm misunderstanding the use case here though.

**Comment by mimxrt** [comment]
Hi @nate-wandb, yes, you are right. Thank you for that, I didn't know/understand this until now.
