### ISSUE TITLE
Python 3.8 import wandb errors

### ISSUE THREAD

**Issue by aus10powell** [wandb/wandb#5747]
### Describe the bug
I'm able to import wandb, however I receive an attribute error in python when I initialize project (e.g. wandb.init())

Currently need to run python 3.8. wandb very useful by not able to wandb.init() (see below)

```python
import wandb
wandb.login()
wandb.init(project="MITFisheryHerring",notes="MIT Fishery robo analytics v1 trying to reporduce success of earlier train38 model")
```

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 2
      1 import wandb
----> 2 wandb.login()
      3 wandb.init(project="MITFisheryHerring",notes="MIT Fishery robo analytics v1 trying to reporduce success of earlier train38 model")

AttributeError: module 'wandb' has no attribute 'login'
```

### Environment

WandB version:
wandb.__version__ failed

OS:
MacOS Ventura 1.34, M2 Pro

Python version:
3.8

Versions of relevant libraries:
None

**Comment by sydholl** [comment]
Internal GitHub User commented: 
### Describe the bug


Currently need to run python 3.8. wandb very useful by not able to wandb.init() (see below)


```python
import wandb
wandb.login()
wandb.init(project="MITFisheryHerring",notes="MIT Fishery robo analytics v1 trying to reporduce success of earlier train38 model")
```


```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 2
      1 import wandb
----> 2 wandb.login()
      3 wandb.init(project="MITFisheryHerring",notes="MIT Fishery robo analytics v1 trying to reporduce success of earlier train38 model")

AttributeError: module 'wandb' has no attribute 'login'
```


### Additional Files

_No response_

### Environment

WandB version:
wandb.__version__ failed

OS:
MacOS Ventura 1.34, M2 Pro

Python version:
3.8

Versions of relevant libraries:
None

### Additional Context

_No response_

**Comment by rsanandres-wandb** [comment]
Hello @aus10powell !

I was able to run `wandb.login()` on `python==3.8` on my my own machine. Your code could be importing a `wandb.py` file instead of the `wandb` package. Could you check to see if there is a `wandb.py` within the same directory that may be conflicting with wandb? If so, move the file into a different directory and this error should go away.

**Comment by aus10powell** [comment]
Thanks for the assistance. There isn't another wandb.py file. I've attached a a screenshot of the directory contents that the command in the Jupyter notebook (training.ipynb) is being run from.

<img width="932" alt="Screenshot 2023-06-20 at 8 40 23 AM" src="https://github.com/wandb/wandb/assets/7726251/50bba0b8-2139-41fe-af44-44d8c4f5f274">

**Comment by aus10powell** [comment]
Follow-up: I've managed to avoid the import issue by creating venv environment (as opposed to the conda environment) and running the training from a python script in a main block vs notebook

**Comment by rsanandres-wandb** [comment]
It looks like there may have been something within your `conda` environment that was importing a different `wandb`. Perhaps it recognized the `wandb` folder as being what you were calling instead of the `wandb` library. However, glad to hear you found a workaround! I will be closing this ticket for now but feel free to open up a new ticket if something else comes up.
