### ISSUE TITLE
Plotting confusion matrix producing Disk quota exceed error

### ISSUE THREAD

**Issue by sarda-devesh** [wandb/wandb#5895]
Hello, 

I recently started using the `wandb.plot.confusion_matrix` functionality inside of a compute cluster and noticed that this causes me to disk quota errors. Specificially, if I run something like this: 
```
# Other code previously

print("Prediction of shape", prediction.shape, "with range [", np.min(prediction), ",", np.max(prediction), "]")
print("Expected of shape", expected.shape, "with range [", np.min(expected), ",", np.max(expected), "]")
print("Have", len(labels), "with values", labels)

'''
if upload:
    wandb.log({ key_name : wandb.plot.confusion_matrix(y_true = expected, preds = prediction, 
                        class_names = list(labels), title = key_name)})
'''

# More code afterwards
```

My runs work properly and complete. However, if I comment the `wand.log` and `wandb.plot.confusion_matrix` call then I get an output as such: 
<img width="896" alt="image" src="https://github.com/wandb/wandb/assets/32046390/3ecf4e98-4d16-4271-a9e2-f08f4a30179e">

I searched for this error and came across #4143 which recommended to update the `WANDB_CACHE_DIR` environment variable. I updated the environment variable and I noticed that the error was still showing up. In order to verify that the environment variable had been set correctly I ran an echo command right afterward when the error showed up and got the following output: 
<img width="531" alt="image" src="https://github.com/wandb/wandb/assets/32046390/b0fdd745-0f8c-4268-9638-6bcebc3cd037">

Since I am working on a remote compute cluster with usage limits, I wanted to make sure that I didn't actually hit limit. Thus, I used `scp` to move a 2.5 GB zip file of my training data from my laptop to `/gscratch/ubicomp/devess/wandb`, the wandb cache dir, in the remote cluster and I noticed I was able to do that without any error. Thus, this indicates that there is plenty of storage in disk so I am really not sure what is causing this issue. I have attached a zip file of the run logs for this run as well: [run-20230714_154249-ztewmypp.zip](https://github.com/wandb/wandb/files/12059064/run-20230714_154249-ztewmypp.zip)

**Comment by sydholl** [comment]
Internal GitHub User commented: 
Hello, 

I recently started using the `wandb.plot.confusion_matrix` functionality inside of a compute cluster and noticed that this causes me to disk quota errors. Specificially, if I run something like this: 
```
# Other code previously

print("Prediction of shape", prediction.shape, "with range [", np.min(prediction), ",", np.max(prediction), "]")
print("Expected of shape", expected.shape, "with range [", np.min(expected), ",", np.max(expected), "]")
print("Have", len(labels), "with values", labels)

'''
if upload:
    wandb.log({ key_name : wandb.plot.confusion_matrix(y_true = expected, preds = prediction, 
                        class_names = list(labels), title = key_name)})
'''

# More code afterwards
```

My runs work properly and complete. However, if I comment the `wand.log` and `wandb.plot.confusion_matrix` call then I get an output as such: 
<img width="896" alt="image" src="https://github.com/wandb/wandb/assets/32046390/3ecf4e98-4d16-4271-a9e2-f08f4a30179e">

I searched for this error and came across #4143 which recommended to update the `WANDB_CACHE_DIR` environment variable. I updated the environment variable and I noticed that the error was still showing up. In order to verify that the environment variable had been set correctly I ran an echo command right afterward when the error showed up and got the following output: 
<img width="531" alt="image" src="https://github.com/wandb/wandb/assets/32046390/b0fdd745-0f8c-4268-9638-6bcebc3cd037">

Since I am working on a remote compute cluster with usage limits, I wanted to make sure that I didn't actually hit limit. Thus, I used `scp` to move a 2.5 GB zip file of my training data from my laptop to `/gscratch/ubicomp/devess/wandb`, the wandb cache dir, in the remote cluster and I noticed I was able to do that without any error. Thus, this indicates that there is plenty of storage in disk so I am really not sure what is causing this issue.

**Comment by sarda-devesh** [comment]
Hello, 

It turns that I had in fact reached my allocated storage capacity and coincidentally rerunning it with the code uncommented made the issue show up. Thus, I am closing this issue as it was not a problem with the API.

**Comment by thanos-wandb** [comment]
Hi @sarda-devesh thanks for the update and glad to hear you've resolved this issue! This is an `OSError` that you've reached your disk quota, which seems was triggered when writing artifacts to your cache directory. Under the hood, the Custom Charts create a wandb.Table which is stored as an artifact. I hope this helps, but please feel free to reopen the ticket if you had any more questions related to this and we will be happy to investigate this more!
