### ISSUE TITLE
[CLI]: Wandb stores wrong step, drops all following logs

### ISSUE THREAD

**Issue by mova** [wandb/wandb#5913]
### Describe the bug

Wandb refuses to log, because it somehow somewhere got a high step and has this step now saved internally.

I pass all of my `wandb.log` calls with the `step=...` option.
For most gradient steps, the number of log calls is 0, but when it's a validation run, it can be 3/4.

Example run: 
https://wandb.ai/hamgen/calochallange/runs/8co7lqyb/overview?workspace=user-mscham

`debug-internal.log`:
```
 2023-07-18 09:17:59,760 WARNING HandlerThread:40897 [handler.py:handle_request_partial_history():553] Step 583600 < 607500. Dropping entry: {'m/speed/          batchtime': 0.01409895420074463, 'm/speed/utilisation': 0.009957877951071526, 'm/speed/processed_events': 291811.0, 'epoch': 208, '_timestamp':                 1689664679.759749}.
```

I traced back where it gets the step from:

https://github.com/wandb/wandb/blob/c50013d6488d393affa89006ace74e7fdb092764/wandb/sdk/internal/handler.py#L713

Apparently a record is passed to the HandlerThread that sets the `_step` attribute to the wrong value. 

### Environment

WandB version: 0.15.5

OS: CentOSLinux7

Python version: 3.10.10

Versions of relevant libraries:

**Comment by rsanandres-wandb** [comment]
Hello @mova !

It looks like you have deleted that run since the time you linked it so unfortunately, I cannot view it. 

As for the logging, `wandb` doesn't allow non-monotonically increasing (in other words, you have to log with each step > last step). Given your setup, are you logging at a step lower than the current step of the run?

Also are you using multiprocessing? When using [distributed training](https://docs.wandb.ai/guides/track/log/distributed-training#share-a-wb-run), we cannot guarantee the logging order so with using hard coded `step=step` in your function, you could be logging at a smaller step.

**Comment by sydholl** [comment]
Raphael San Andres commented: 
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
