### ISSUE TITLE
[Q] Continue training with HF Transformers

### ISSUE THREAD

**Issue by BramVanroy** [wandb/wandb#5937]
Using the integration in Hugging Face Transformers `Trainer`, how can I easily continue training? I can **not** make code changes but I am able to pass config options or set environment variables if that is needed. Is it sufficient to just set `WANDB_DIR` to the same value for the second run, and will that then automatically continue the previous run?

I found this (https://docs.wandb.ai/guides/runs/resuming) but it seems that code changes are necessary (resume=True), which is very inconvenient for my use case (in a SLURM environment). I also found this reference (https://docs.wandb.ai/guides/integrations/huggingface#resume-training-from-a-checkpoint) but it does not use the HF Trainer.

I opened a related issue on the `transformers` side. I can work on integrating this but feedback from the wandb team is welcome. https://github.com/huggingface/transformers/issues/25032

**Comment by umakrishnaswamy** [comment]
Hey @BramVanroy, since you are running this in a SLURM environment and unable to make code changes, I recommend changing the environment variables associated with resuming runs to ensure that your run resumes from a specific ID: 

`WANDB_RESUME` is by default set to never, so you can change this to 'must' along with setting `WANDB_PROJECT` to the appropriate project, and `WANDB_RUN_ID` to the run_id with the run you are trying to resume. You can do this prior to running your script. 

Documentation can be found [here](https://docs.wandb.ai/guides/track/environment-variables#optional-environment-variables), along with other environment variables you can set prior to training. I hope this helps! Please let me know if you have any further questions.

**Comment by sydholl** [comment]
Uma Krishnaswamy commented: 
Hi @BramVanroy, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
