### ISSUE TITLE
[CLI/Web]: wandb suddenly Not Uploading Images

### ISSUE THREAD

**Issue by eliphatfs** [wandb/wandb#5949]
### Describe the bug

From several hours before writing wandb stops uploading images. The same code worked well yesterday.

```python
wandb.log({"image": [pil_image], "lpips": lpips_mean})
```
The values are seen, but images are not uploaded. There are no images in files panel or chart UI.
However, I can see the images in the run folder, thus I must have called wandb in my script successfully.

The issue seems a regression of #5332.

![image](https://github.com/wandb/wandb/assets/23738781/d768e910-a55d-43ab-88f1-1a7059cb7dc7)
![image](https://github.com/wandb/wandb/assets/23738781/8977d784-2008-461d-b8f8-208670f830f0)
![image](https://github.com/wandb/wandb/assets/23738781/0ea7388b-5c14-40bd-a534-8fc01a70e200)

### Environment

WandB version: 0.15.6

OS: Linux

Python version: 3.7.13

Versions of relevant libraries:
- `Accelerate` version: 0.20.3
- Platform: Linux-5.3.0.release.104.782985b880c9-x86_64-with-debian-buster-sid
- Numpy version: 1.21.5
- PyTorch version (GPU?): 1.12.1 (True)

**Comment by sydholl** [comment]
Internal GitHub User commented: 
### Describe the bug


From several hours before writing wandb stops uploading images. The same code worked well yesterday.


```python
wandb.log({"image": [pil_image], "lpips": lpips_mean})
```
The values are seen, but images are not uploaded. There are no images in files panel or chart UI.
However, I can see the images in the run folder, thus I must have called wandb in my script successfully.

The issue seems a regression of #5332.

![image](https://github.com/wandb/wandb/assets/23738781/d768e910-a55d-43ab-88f1-1a7059cb7dc7)
![image](https://github.com/wandb/wandb/assets/23738781/8977d784-2008-461d-b8f8-208670f830f0)
![image](https://github.com/wandb/wandb/assets/23738781/0ea7388b-5c14-40bd-a534-8fc01a70e200)



### Additional Files

_No response_

### Environment

WandB version: 0.15.6

OS: Linux

Python version: 3.7.13

Versions of relevant libraries:
- `Accelerate` version: 0.20.3
- Platform: Linux-5.3.0.release.104.782985b880c9-x86_64-with-debian-buster-sid
- Numpy version: 1.21.5
- PyTorch version (GPU?): 1.12.1 (True)

### Additional Context

_No response_

**Comment by ludwigwinkler** [comment]
+1

**Comment by thanos-wandb** [comment]
Hi @eliphatfs @ludwigwinkler thanks so much for reporting this issue. I was able to reproduce the issue with the following code, but the images will sync once you call `wandb.finish()`. Is it the same behavior you're experiencing, or the images won't sync at all for you? I will escalate it to our SDK team and will keep you posted here. 

If it's important to sync your images in real time, would it work for you to downgrade to `wandb v0.15.5` for now?

```
import numpy as np
from PIL import Image as PILImage
import wandb

wandb.init()
examples = []
for i in range(3):
 pixels = np.random.randint(low=0, high=256, size=(100, 100, 3), dtype=np.uint8)
 pil_image = PILImage.fromarray(pixels, mode="RGB")
 image = wandb.Image(pil_image, caption=f"random field {i}")
 examples.append(image)
wandb.log({"examples": examples})
```

The images will sync when calling `wandb.finish()`.

**Comment by eliphatfs** [comment]
Thanks @thanos-wandb, I confirmed that when I hit the stop run button in wandb, after the experiment stopped the images appeared.

**Comment by thanos-wandb** [comment]
Hi @eliphatfs @ludwigwinkler our SDK team identified the PR that caused this regression, and reverted it. The SDK team just released `v0.15.7 ` ([release notes here](https://github.com/wandb/wandb/releases/tag/v0.15.7)) where this issue should be addressed. Please let us know if you're still experiencing this issue after you `pip install --upgrade wandb`.  Thanks so much for reporting!

**Comment by henrik-schopmans** [comment]
I am experience the same problem, also on v0.15.7

**Comment by eliphatfs** [comment]
Then maybe we are not having the same problem, my images were showing when I switched back to 0.15.5

**Comment by henrik-schopmans** [comment]
You are right, sorry. My problem is resolved now, I had a stupid bug in my code ^^.

**Comment by eliphatfs** [comment]
Thanks! The problem seems gone, closing for now. My guess is that the problem is caused by the comment-out of `PolicyNow` in https://github.com/wandb/wandb/pull/5777/files#diff-5d784175e3102d93c64d3e60d67db77985409ab34e81452a4bb3033e84731737L318

**Comment by thanos-wandb** [comment]
Hi @eliphatfs that's correct, we've reverted this PR due to this bug that was introduced, and the specific PR will go out in our next SDK release. Thanks so much for reporting!
