### ISSUE TITLE
[Q] Group histograms across runs or show multiple histograms?

### ISSUE THREAD

**Issue by StoneT2000** [wandb/wandb#6021]
Was wondering if there was a way to see multiple histograms overlayed each other from different runs? Or group / average the histograms if that makes sense

<img width="1676" alt="Screen Shot 2023-08-07 at 7 35 27 PM" src="https://github.com/wandb/wandb/assets/35373228/c35b374d-3e5e-498d-af20-c385805a8877">

It seems only the first one is shown.

Thanks!

**Comment by rsanandres-wandb** [comment]
Hello @StoneT2000 !

The best way I can recommend is to add them to a report and add both run sets to the same panel. (See the picture). 
<img width="1045" alt="image" src="https://github.com/wandb/wandb/assets/122482606/a9126b4b-7b8d-4ba4-b0df-1d2c72f24190">

This should plot the aggregates of all histograms of the same name. The important thing to note is that the histograms must have the same name in order for this type of grouping to work since the y-axis of the graph is dependent on one value and it isn't possible to add multiple histograms of different names.

**Comment by sydholl** [comment]
Raphael San Andres commented: 
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
