### ISSUE TITLE
[App]: WSL error when following Job Launch Walkthrough 

### ISSUE THREAD

**Issue by OfficeLlama** [wandb/wandb#6092]
### Current Behavior

Following the steps given in https://docs.wandb.ai/guides/launch/walkthrough, after queuing a job successfully on the web app, the agent receives the job but errors. A section of my cmd output shows:

```
wandb: launch: Launching run in docker with command: docker run --rm -e WANDB_BASE_URL=https://api.wandb.ai -e WANDB_API_KEY -e WANDB_PROJECT=launch-quickstart -e WANDB_ENTITY=[REDACTED] -e WANDB_LAUNCH=True -e WANDB_RUN_ID=ljwn6ne5 -e WANDB_USERNAME=[REDACTED] -e WANDB_CONFIG='{"epochs": 10}' -e WANDB_ARTIFACTS='{"_wandb_job": "[REDACTED]/launch-quickstart/job-source-launch-quickstart-train.py:latest"}' [REDACTED]__launch-quickstart__job-source-launch-quickstart-train.py:0333b4af
<3>WSL (2912) ERROR: CreateProcessEntryCommon:577: execvpe /bin/bash failed 2
<3>WSL (2912) ERROR: CreateProcessEntryCommon:586: Create process not expected to return
```

### Expected Behavior

The job runs successfully on my local machine

### Steps To Reproduce

Follow instructions at [link](https://docs.wandb.ai/guides/launch/walkthrough)

### Environment

OS: Windows 10

Browsers: Chrome Version 116.0.5845.96 (Official Build) (64-bit)

Version: wandb, version 0.15.5

wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3324

**Comment by sydholl** [comment]
Internal GitHub User commented: 
### Current Behavior

Following the steps given in https://docs.wandb.ai/guides/launch/walkthrough, after queuing a job successfully on the web app, the agent receives the job but errors. A section of my cmd output shows:

```
wandb: launch: Launching run in docker with command: docker run --rm -e WANDB_BASE_URL=https://api.wandb.ai -e WANDB_API_KEY -e WANDB_PROJECT=launch-quickstart -e WANDB_ENTITY=[REDACTED] -e WANDB_LAUNCH=True -e WANDB_RUN_ID=ljwn6ne5 -e WANDB_USERNAME=[REDACTED] -e WANDB_CONFIG='{"epochs": 10}' -e WANDB_ARTIFACTS='{"_wandb_job": "[REDACTED]/launch-quickstart/job-source-launch-quickstart-train.py:latest"}' [REDACTED]__launch-quickstart__job-source-launch-quickstart-train.py:0333b4af
<3>WSL (2912) ERROR: CreateProcessEntryCommon:577: execvpe /bin/bash failed 2
<3>WSL (2912) ERROR: CreateProcessEntryCommon:586: Create process not expected to return
```

### Expected Behavior

The job runs successfully on my local machine

### Steps To Reproduce

Follow instructions at [link](https://docs.wandb.ai/guides/launch/walkthrough)

### Screenshots

_No response_

### Environment

OS: Windows 10

Browsers: Chrome Version 116.0.5845.96 (Official Build) (64-bit)

Version: wandb, version 0.15.5

wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3324

### Additional Context

_No response_

**Comment by umakrishnaswamy** [comment]
@OfficeLlama Do you reach this same error when updating your SDK version to our latest? Additionally, did you create a Starter queue and is this where you're running into the error? I.e. does this behavior occur when you run something like:

`wandb launch-agent -e <entity-name> -q <queue-name>`

**Comment by sydholl** [comment]
Uma Krishnaswamy commented: 
Hi @OfficeLlama, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by umakrishnaswamy** [comment]
Hi @OfficeLlama, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
