### ISSUE TITLE
[App]: Logging metric with the name "length" breaks summary in web app

### ISSUE THREAD

**Issue by keraJLi** [wandb/wandb#6108]
### Current Behavior

When logging a metric called "length", the summary of metrics shows 200 keys named "0", "1", ..., "199" which all have the value "null", and nothing else. Clicking on "View raw data" simply shows "{}". Expressions using the summary don't work as well, but the summary is recorded correctly when accesses via the python API.

### Expected Behavior

In the web app, the summary should show "length": "...", as well as other metrics.

### Steps To Reproduce

1. Run
```python
import wandb
wandb.init(project="...", entity="...", config={}, name="length-bug")
wandb.log({'length': 200.0})
```
2. Go to the run page
3. Click on "overview".

### Screenshots

![grafik](https://github.com/wandb/wandb/assets/14016149/db0b069b-4378-4427-ba84-1bdf59ecfe8c)
![grafik](https://github.com/wandb/wandb/assets/14016149/f6db7bb5-e3f9-4671-906c-049f40d2d6fa)

### Environment

OS: Windows

Browsers: Firefox

Version:116.0.3 (64-Bit)

**Comment by sydholl** [comment]
Internal GitHub User commented: 
### Current Behavior

When logging a metric called "length", the summary of metrics shows 200 keys named "0", "1", ..., "199" which all have the value "null", and nothing else. Clicking on "View raw data" simply shows "{}". Expressions using the summary don't work as well, but the summary is recorded correctly when accesses via the python API.

### Expected Behavior

In the web app, the summary should show "length": "...", as well as other metrics.

### Steps To Reproduce

1. Run
```python
import wandb
wandb.init(project="...", entity="...", config={}, name="length-bug")
wandb.log({'length': 200.0})
```
2. Go to the run page
3. Click on "overview".

### Screenshots

![grafik](https://github.com/wandb/wandb/assets/14016149/db0b069b-4378-4427-ba84-1bdf59ecfe8c)
![grafik](https://github.com/wandb/wandb/assets/14016149/f6db7bb5-e3f9-4671-906c-049f40d2d6fa)


### Environment

OS: Windows

Browsers: Firefox

Version:116.0.3 (64-Bit)


### Additional Context

_No response_

**Comment by umakrishnaswamy** [comment]
@keraJLi Thank you for flagging this. I was able to reproduce this behavior on my end and will flag this as a bug. I'll let you know if any progress on this arises by updating this thread.

**Comment by sydholl** [comment]
WandB Internal User commented: 
umakrishnaswamy commented: 
@keraJLi Thank you for flagging this. I was able to reproduce this behavior on my end and will flag this as a bug. I'll let you know if any progress on this arises by updating this thread.

**Comment by umakrishnaswamy** [comment]
hey @keraJLi - as a workaround in the meantime, would it be possible to use Chrome? I was able to get this working on that browser, thanks again!

**Comment by keraJLi** [comment]
I strongly prefer using Firefox. As an alternative workaround, I've renamed the key from `length` to something else (e.g. `length_`). 
Still, I believe that this bug should be fixed in Firefox too.

**Comment by umakrishnaswamy** [comment]
understood - Are you still encountering this issue on Firefox? I was able to circumvent the issue by logging a new run on our latest SDK and viewing the run Overview page in Firefox. Would it be possible to confirm if the issue is still persisting on your end?

**Comment by keraJLi** [comment]
The key displays correctly for me now. Thank you very much for fixing it! 🚀
