### ISSUE TITLE
[Q] question of x-axis indexing

### ISSUE THREAD

**Issue by Yeah2333** [wandb/wandb#6218]
Hi, i using wandb to track some data. The data is log using  `wandb.log({"UTC_Time": NoGtErrors["UTC_Time"][i], "Error Ratio(%)": NoGtErrors["error_ratio"][i] * 100})`. The UTC_ Time is obtained by multiplying the unix timestamp by 1e6 and rounding it. And UTC_Time as x_axis, Error Ratio as y_axis. When track data in wandb, the x_axis has different value(very big difference). In figure, i select same place. But one x_axis is 1691056204679010 and another is 1691056203778872 Why this happen?
![image](https://github.com/wandb/wandb/assets/22851247/0e42bfd8-725e-4166-9edf-d5e1745f99cf)

**Comment by umakrishnaswamy** [comment]
Hey @Yeah2333, to make sure I'm understanding correctly, you are wondering why the step value you are viewing is different between the two lines when you hover over? 

Could you send over a link to the workspace you are referring to? I would love to take a closer look at what's going on.

**Comment by Yeah2333** [comment]
@umakrishnaswamy Hi, what you understand is correct, i wondering why the step value why step value is different between experiment when i houver over. My wandb is deployed locally. Sorry for that, i can't give you workspace's link. What are the possible solutions for step value？

**Comment by umakrishnaswamy** [comment]
Hey @Yeah2333, this is likely due to how we sample if you are logging more than 1500 points in a line plot. When over 1500 points are chosen for a line plot metric, W&B returns 1500 randomly sampled points. Each metric is sampled separately and only steps where the metric is actually logged are considered. Documentation can be found [here](https://docs.wandb.ai/guides/app/features/panels/line-plot/sampling#sampling)

If you want to look at all of the metrics logged for a run or implement your own sampling you can use the W&B Api.

**Comment by Yeah2333** [comment]
@umakrishnaswamy hi, thank you for your reply. I am very pleased to receive your discussion on this issue In fact, this issue is quite important, especially when the training time is relatively long.

**Comment by umakrishnaswamy** [comment]
@Yeah2333 Thank you for your kind words! I'll close this ticket for now, but I'll be sure to write back in this thread if we make changes to this behavior
