### ISSUE TITLE
[App]: chart edits are not shared between the Runs page and the run-specific page

### ISSUE THREAD

**Issue by rfernand2** [wandb/wandb#6245]
### Current Behavior

If I make a change to a chart of a run from the Project | Runs page, those changes are not reflected in the charts for the run-specific page.  Likewise, edits made to a chart of the run-specific page are not shared with the Project | Runs page for that run.  I tried using F5 to refresh each of the pages, but changes are still not shared.

### Expected Behavior

I expect what I see on the Runs page for the selected run to be reflected in the run-specific page.

### Steps To Reproduce

1. Go to a Runs page for a project and select a run
2. Click on the edit button for a chart and change the chart type (say from Line to Area)
3. Click OK and see the new chart type reflected on the Runs page.
4. Now click on the run in the Runs panel to go to the page for that run
5. The change you made to the chart should be reflected here but is not.

### Screenshots

<img width="1309" alt="image" src="https://github.com/wandb/wandb/assets/4296158/f42f1a33-438e-4032-bcd3-0d207540841b">

<img width="1319" alt="image" src="https://github.com/wandb/wandb/assets/4296158/5ddb52b8-8a79-4358-84b3-0ff941b58d6a">

### Environment

OS: Windows 11

Browsers: Chrome

Version:

**Comment by rsanandres-wandb** [comment]
Hello @rfernand2!

Happy to help!

This is currently expected behavior since each workspace will have its own pre-existing changes done to it. When moving from the project level (the Runs page) to the run itself, the workspace will be different which means that the changes will not be transferred. The main reason for this is that the base data for runs page vs the individual run is different since the project deals with the runs data combined into while the individual run takes a row of the run. 

However, I can certainly make a feature request to create a way to automatically import charts from the Runs page workspace to the individual runs if that interests you.

**Comment by rfernand2** [comment]
Hi @rsanandres-wandb.  Thanks for your explanation - I didn't realize that the "runs" page was a multirun viewer until earlier today.  It makes sense to have them separate.  I'll close this now.
