### ISSUE TITLE
[App]: Some graphs not showing up

### ISSUE THREAD

**Issue by BramVanroy** [wandb/wandb#6279]
### Current Behavior

My section has 9 graphs. This is correctly written on the top left but on the bottom right I cannot scroll/click to it. On the bottom left it says only two are available. This means I cannot click through to the other graphs and I am stuck with only the first.

### Expected Behavior

Being able to click through

### Steps To Reproduce

This is the first time that it has ever happened to me. Not sure what is different other than that I am using my work laptop. It has a 1920x1200 resolution and 150% scaling enabled.

This happens in the simple project view where you get an overview of the graphs of the runs.

CORRECTION: it also occurs on mobile 

### Screenshots

![image](https://github.com/wandb/wandb/assets/2779410/4b4e42ee-ca94-4854-bb43-408474535be9)

### Environment

OS:
Windows 11
Browsers:
Edge
Version:
Version 116.0.1938.76 (Official build) (64-bit)

**Comment by ArtsiomWB** [comment]
Hi @BramVanroy! Thank you for writing in! Could you please send me a link to your workspace where you are encountering this behavior?

**Comment by BramVanroy** [comment]
Hi @ArtsiomWB Thanks for the quick reply. Sure, you can find it here: https://wandb.ai/bramvanroy/amr_es_nl

Interestingly, when I visit that link in a private tab (so no cookies/not logged in), everything seems to work fine...

**Comment by BramVanroy** [comment]
So, interestingly:

- this works: https://wandb.ai/bramvanroy/amr_es_nl?workspace=user-
- this is bugged: https://wandb.ai/bramvanroy/amr_es_nl?workspace=user-bramvanroy

I tried resetting the workspace to default with the button at the bottom but that did not help. Also tried removing cookies and logging in/out. No avail. @ArtsiomWB

**Comment by ArtsiomWB** [comment]
Hi @BramVanroy! I think I see where the issue is coming from. In the screenshot you've sent above I see letter `i` being highlighted in the name of your graph in eval/runtime. If you go into your workspace, inside of your search bar, it looks like you are searching for the letter `i`, and therefore only 2/9 graphs show up in that section because they have `i` in their names. 

<img width="1006" alt="image" src="https://github.com/wandb/wandb/assets/115654725/276c1c19-b827-4dc6-9175-0fbf63a0ba4f">

**Comment by sydholl** [comment]
WandB Internal User commented: 
BramVanroy commented: 
So, interestingly:

- this works: https://wandb.ai/bramvanroy/amr_es_nl?workspace=user-
- this is bugged: https://wandb.ai/bramvanroy/amr_es_nl?workspace=user-bramvanroy

I tried resetting the workspace to default with the button at the bottom but that did not help. Also tried removing cookies and logging in/out. No avail. @ArtsiomWB

**Comment by sydholl** [comment]
WandB Internal User commented: 
ArtsiomWB commented: 
Hi @BramVanroy! I think I see where the issue is coming from. In the screenshot you've sent above I see letter `i` being highlighted in the name of your graph in eval/runtime. If you go into your workspace, inside of your search bar, it looks like you are searching for the letter `i`, and therefore only 2/9 graphs show up in that section because they have `i` in their names. 

<img width="1006" alt="image" src="https://github.com/wandb/wandb/assets/115654725/276c1c19-b827-4dc6-9175-0fbf63a0ba4f">

**Comment by BramVanroy** [comment]
Oh god, indeed, there was a I in the search bar that I hadn't noticed. Such a silly mistake. Thanks a lot and apologies for the silly error.
