### ISSUE TITLE
[App]: Artifacts seem to be unavailable after moving a run to a new project and deleting the old one

### ISSUE THREAD

**Issue by TreeMage** [wandb/wandb#6285]
### Current Behavior

I moved two runs to an already existing project and deleted the old project. Afterwards, the artifacts logged for these runs still appear in the Web UI but do not seem to be actually present. Cicking on an artifact in the Web UI results in a 404 Error page. 
Trying to donwload them via the python library using `wandb.use_artifact` results in a `wandb.errors.CommError: Permission denied` Error.

### Expected Behavior

I would expect artifacts of moved runs to be available via the new project.

### Steps To Reproduce

1. Move a run to a different project.
2. Access its artifacts via the Web UI / python library.
3. 404/ Permission Denied

### Environment

OS: macOS Ventura 13.4.1 (c) (22F770820d)

Browsers: Firefox

Version: 0.15.7

**Comment by thanos-wandb** [comment]
Hi @TreeMage thanks for reporting this issue, and sorry to hear about it. This happened because we won't move the underlying artifacts when moving the run to a new project. Could you please go to the project's overview page, and click undelete runs? how many days ago did you delete that? 

If you wanted to move the artifacts too, you could use our [importer tool](https://docs.wandb.ai/guides/track/public-api-guide#import-data-from-another-wb-instance) (please note it currently only works with `wandb 0.15.6`). Please see below a code example on its usage:

`!pip install wandb==0.15.6 polars tqdm`

And then run the following code snippet:

```import wandb
wandb.login()

from wandb.apis.importers import WandbParquetImporter

importer = WandbParquetImporter(
    src_base_url="https://api.wandb.ai/",
    src_api_key="your-wandbai-key",
    dst_base_url="https://api.wandb.ai/",
    dst_api_key="your-wandbai-key",
)


src_entity='entity-original'
dst_entity='entity-destination'
src_project='project-original'
dst_project='project-destination'


importer.import_all_runs(
    src_entity,
    src_project,
    overrides={
        'entity': dst_entity,
        'project': dst_project
    }
)```

**Comment by TreeMage** [comment]
Hey @thanos-wandb, thanks for the quick reply. I think I deleted the project a while ago so undelete probably won't work, but I'll give the import solution a try! I find this behavior rather counterintuitive (especially the fact that the artifacts still show up in the web UI and produce a permission denied error during a download attempt). 

Maybe this should be changed/documented?

Anyways, thank you for the quick support and feel free to close this issue :)

**Comment by thanos-wandb** [comment]
Thank you @TreeMage for the feedback. I will make a Docs update request, as I agree it isn't intuitive for our users. I will close this ticket now but please feel free to reach out had you have any other questions :)
