### ISSUE TITLE
[App]: ctrl+c feature on plots stopped working

### ISSUE THREAD

**Issue by albertfgu** [wandb/wandb#6372]
### Current Behavior

Pressing Cmd+C (on Mac) when hovering over a figure no longer shows the actual numbers. It just shows all the run names.

### Expected Behavior

Previously, pressing Cmd+C (on Mac) would copy paste all the numbers

### Environment

OS: macOS

Browsers: Chrome

Version:

**Comment by sydholl** [comment]
Internal GitHub User commented: 
### Current Behavior

Pressing Cmd+C (on Mac) when hovering over a figure no longer shows the actual numbers. It just shows all the run names.

### Expected Behavior

Previously, pressing Cmd+C (on Mac) would copy paste all the numbers

### Steps To Reproduce

_No response_

### Screenshots

_No response_

### Environment

OS: macOS

Browsers: Chrome

Version:


### Additional Context

_No response_

**Comment by rsanandres-wandb** [comment]
Thank you for reporting this! I have made a bug report for our team to look at.

**Comment by rsanandres-wandb** [comment]
Hello! Our App team has fixed this bug so I will be closing this thread now. Let me know if this does not work and we can revisit this thread 😄

**Comment by albertfgu** [comment]
Hi, I think that there is still an issue. I haven't used this feature in the past week so I'm not sure if it was fixed and then regressed, or never fixed at all; but for me at least it's not currently working.
