### ISSUE TITLE
[CLI]: wandb sync on deleted run causes infinite loop  `previously created and deleted; try a new run name (<Response [409]>))`

### ISSUE THREAD

**Issue by klieret** [wandb/wandb#6395]
### Describe the bug

**Reproduce**

1. Create run with wandb set to offline
2. sync it with `wandb sync`
3. Delete run in web API
4. Run `wandb sync` again

**Expectation**: Wandb CLI quits with an error

**What happens instead**: Wandb CLI gets stuck in a seemingly endless loop, outputting

```
wandb: ERROR Error while calling W&B API: run gnn_tracking/gnn_tracking/industrious-optimal-ringtail was previously created and deleted; try a new run name (<Response [409]>)
```

### Environment

WandB version: 0.15.11

OS: Linux

```
LSB Version:    :core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-ia32:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-ia32:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Springdale
Description:    Springdale Linux release 8.8 (Modena)
Release:        8.8
Codename:       Modena
```

Python version: 3.10.11

Versions of relevant libraries:

### Additional Context

Possibly related to https://github.com/wandb/wandb/issues/1192

**Comment by nate-wandb** [comment]
Hi @klieret, I was able to reproduce this as well. The problem is that the run_id still exists in the backend (indeed related to the issue you linked). I'll have the team look into this but in the meantime you can solve this by passing a new id to the run with the `--id` flag: `wandb sync <path/to/run> --id <new 8-digit id>`

**Comment by nate-wandb** [comment]
Hi @klieret, this behavior is likely something that won't change because we allow recovering deleted runs for up to 7 days after the run is deleted so we need to reserve those run_id's during that time period so the original runs can be recovered if needed. Do you think passing a new id is a reasonable workaround or is there another behavior you would like to see?

**Comment by ductai199x** [comment]
I think it would be better to let user have the option to hard delete runs instead of soft deleting on the front end and lying about it in the back end. It makes users like me become confused about what is happening and reluctant to use the platform further

**Comment by klieret** [comment]
> Hi @klieret, this behavior is likely something that won't change because we allow recovering deleted runs for up to 7 days after the run is deleted so we need to reserve those run_id's during that time period so the original runs can be recovered if needed. Do you think passing a new id is a reasonable workaround or is there another behavior you would like to see?

Hi @nate-wandb, thanks for reaching out again, I really appreciate that you try to find a solution that works for everyone.

In my particular case, I didn't actually care about the run itself; I was looping over all the directories of the offline runs to sync them. If `wandb sync` had simply refused to sync the run and then quit, this would not have been a problem. However, it stuck in a retry loop, so I had to manually take care of this case (by removing the directory).

So I think the bug here is that it's stuck in a loop instead of quitting with an error message.

**Comment by wodelt** [comment]
wandb version 0.18.1
solution:

first get a generate_id
python -c "import wandb; print(wandb.util.generate_id())"
than:
export WANDB_RUN_ID=generate_id

and re-run you .py should be worked

**Comment by ShaoZhenLiu** [comment]
When I using this command: `wandb sync <path/to/run> --id <new 8-digit id>`
I get the error: `wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)`

**Comment by luisbergua** [comment]
Hi @ShaoZhenLiu, thanks for sharing this! `0.12.11` is an old version, so I would recommend upgrading with `pip install wandb -U`. Please let me know if that helps!

**Comment by luisbergua** [comment]
Hey @ShaoZhenLiu, I wanted to confirm that this issue doesn't happen in our latest version `0.18.7`. Will mark this as resolved, please feel free to re-open if you still see the issue!

**Comment by yyc25** [comment]
> Hi [@klieret](https://github.com/klieret), I was able to reproduce this as well. The problem is that the run_id still exists in the backend (indeed related to the issue you linked). I'll have the team look into this but in the meantime you can solve this by passing a new id to the run with the `--id` flag: `wandb sync <path/to/run> --id <new 8-digit id>`

nice!

**Comment by paulpacaud** [comment]
1. I deleted runs in the web UI
2. I run wandb sync --sync-all --include-offline --verbose wandb locally
3. I get the looping error wandb: ERROR Error while calling W&B API: run pym7msz1 was previously created and deleted; try a new run id (<Response [409]>)

If I deleted them in the web UI the sync-all should not try to sync it again, are you sure the bug is resolved?
I use wandb 0.22.1
