### ISSUE TITLE
[App]: Can delete a team

### ISSUE THREAD

**Issue by haewonc** [wandb/wandb#6486]
### Current Behavior

I cannot find a delete button in a team page.
My wandb username is haewonc, and the team name is protein-group.
Thank you.

### Expected Behavior

Delete the team

### Environment

OS: Mac

Browsers: Chrome

Version:

**Comment by JoanaMarieL** [comment]
Hello @haewonc ,

Happy to assist this concern.

Thank you for providing the details of your profile. Are you looking for the Delete button to delete the protein-group team? We will look into your roles first to see why it is not visible in your end. Will keep you posted.

**Comment by haewonc** [comment]
Yes, I am trying to delete the protein-group team. I am the admin and the only member of the group. Thank you!

**Comment by JoanaMarieL** [comment]
Hello @haewonc ,

We understand that you are trying to delete the protein-group team but could not find the Delete Button. We will review your profile and will follow up.

**Comment by MBakirWB** [comment]
Hi @haewonc , appreciate your patience as we looked into this. I've deleted your team protein-group. The reason you didn't see the delete button is the team settings page was locked out due to the trial team being above it's tracked hours limit. We will investigate how best to handle you opting out of a trial team. Marking resolved but please do reach out again if you require further assistance.
