### ISSUE TITLE
[Q] Same metric but against multiple different x-axis

### ISSUE THREAD

**Issue by sytelus** [wandb/wandb#6510]
I wish to plot same metric, say `train/loss` but again two different x-axis, for example, `step` and `tokens`. This should appear as two different plots showing loss against steps and loss against  tokens. How do I do this?

Currently, I do:

```
wandb.define_metric("step")
wandb.define_metric("tokens")

wandb.define_metric("train/loss", step_metric="step")
wandb.define_metric("train/loss", step_metric="tokens")
```

However, it seems 2nd definition overwrites the first instead of treating it different. 

I need to do this for a whole lot of metrics for tons of runs and so fudging around in wandb UX is not an option.

**Comment by sydholl** [comment]
Internal GitHub User commented: 
I wish to plot same metric, say `train/loss` but again two different x-axis, for example, `step` and `tokens`. This should appear as two different plots showing loss against steps and loss against  tokens. How do I do this?

Currently, I do:

```
wandb.define_metric("step")
wandb.define_metric("tokens")

wandb.define_metric("train/loss", step_metric="step")
wandb.define_metric("train/loss", step_metric="tokens")
```

However, it seems 2nd definition overwrites the first instead of treating it different. 

I need to do this for a whole lot of metrics for tons of runs and so fudging around in wandb UX is not an option.

**Comment by thanos-wandb** [comment]
Hi @sytelus thank you for writing in! Just to confirm, are you doing something similar to the code snippet below:

```
import wandb

wandb.init(project='define-metric')

wandb.define_metric("step")
wandb.define_metric("tokens")

wandb.define_metric("train/loss", step_metric="step")
wandb.define_metric("train/loss", step_metric="tokens")

for i in range(10):
    log_dict = {
        "train/loss": 1 / (i + 1),
        "step": i**2,
        "tokens": i**4,
    }
    wandb.log(log_dict)

wandb.finish()
```

and then in the UI you only get one plot? this is currently the expected behavior as it creates one plot per y-axis metric, eg `train/loss` and not per x-axis variable. However, you could `Add panel` > `Line plot` in the App and plot against the other custom metric too. Would this not work for you?

**Comment by thanos-wandb** [comment]
Hi @sytelus we wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by sytelus** [comment]
Hi, I want to automatically create two plots for same y-axis but different x-axis. How can we do this using APIs (without having to use UX).

**Comment by thanos-wandb** [comment]
Hi @sytelus thank you for the additional context. You will need to log the plots under a different key. I have provided you with a code snippet to achieve this. Can you please try this and let us know if that works for you?

```
wandb.init(project='define-metric')

wandb.define_metric("step")
wandb.define_metric("tokens")

wandb.define_metric("train/loss_step", step_metric="step")
wandb.define_metric("train/loss_tokens", step_metric="tokens")

for i in range(10):
    log_dict = {
        "train/loss_step": 1 / (i + 1),
        "train/loss_tokens": 1 / (i + 1),
        "step": i**2,
        "tokens": i**4,
    }
    wandb.log(log_dict)

wandb.finish()
```

**Comment by sytelus** [comment]
I see. This hack won't generate nice clean plots but it's good workaround for the current limitation. I really feel wandb needs API that allows to specify plots configuration separately. That is, you can log any (key, value) pairs but specify the plots configuration in init. The plot configurations should setup x-axis, y-axis, legends, multiple plots in same figure, order of plots etc. 

Thanks for the response.

**Comment by thanos-wandb** [comment]
Hi @sytelus thank you for your valuable feedback, and good to hear that the current solution is meeting your needs for now. Your suggestion is greatly appreciated, and I will log it as a feature request for our engineering team to consider.

Currently, it's possible to achieve the desired functionality by utilizing the Reports API to create and configure the plots within the Reports section, rather than in the Workspaces. For further information, you can refer to our documentation page and find a helpful [Colab example here](https://docs.wandb.ai/guides/reports/create-a-report).

Thank you once again for your input, and we'll keep you updated on any developments regarding this feature request.

**Comment by sytelus** [comment]
Thanks. Reporting API is unfortunately not a solution. We do training runs and share it among large set of people so everyone can see what is going on. The plots needs to be configurable for each run.

**Comment by thanos-wandb** [comment]
Hi @sytelus just for your information, this has been filed as a feature request, and we will keep you updated on its progress here. Thank you for this suggestion!

**Comment by sytelus** [comment]
Thanks.

**Comment by sytelus** [comment]
Hi, wondering if there are any improvements in APIs for this very old feature request. Ability to plot metric against step, tokens and time is super basic ability that people need, in my opinion.

**Comment by thanos-wandb** [comment]
Regarding the original request here, it still isn't possible to use multiple x-axis variables against a y-axis metric. But last week we added support to allow use non-monotonic steps in the x-axis, so I was wondering if inverting x/y axes would help with this ask?

**Comment by thanos-wandb** [comment]
Hi @sytelus since we have not heard back from you, and the Workspaces API should address the request to perform this programmatically, we are going to close this request. If you would like to re-open the conversation, please let us know - and we would be more than happy to help any further!
