### ISSUE TITLE
[App]: Select runs that logged image with the key validation to visualize data here.

### ISSUE THREAD

**Issue by xiaowen0110** [wandb/wandb#6584]
### Current Behavior

<img width="1321" alt="image" src="https://github.com/wandb/wandb/assets/38575973/42ccc2da-50f7-4aac-a666-4ac01627ac7b">
<img width="1310" alt="image" src="https://github.com/wandb/wandb/assets/38575973/8c6bbd4e-d73d-499d-a5e5-4f32515f0855">

### Steps To Reproduce
when i delete the media tab and add it again. The old experiment will show the image log but all new experiment will not. I look up some same issue but it don't work. (I have tried some version of wandb=0.15.7, 0.15.8, 0.16.0 ... etc)
_No response_

### Environment

OS: macos12.1 in cloud; Ubuntu 18.04.3 LTS in localy

Browsers: chrome

Version: wandb==0.15.7, python==3.10

**Comment by sydholl** [comment]
Internal GitHub User commented: 
### Current Behavior

<img width="1321" alt="image" src="https://github.com/wandb/wandb/assets/38575973/42ccc2da-50f7-4aac-a666-4ac01627ac7b">
<img width="1290" alt="image" src="https://github.com/wandb/wandb/assets/38575973/c9adb092-18a2-4373-9894-6d95f82cb71b">
when i delete this tab and add it again. The old experiment will show the image log but all new experiment will not. I look up some same issue but it don't work. (I have tried some version of wandb=0.15.7, 0.15.8, 0.16.0 ... etc)

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Screenshots

_No response_

### Environment

OS:

Browsers:

Version:


### Additional Context

_No response_

**Comment by Carlo-Argel** [comment]
Hi @xiaowen0110 ,

Thank you for reaching out. I appreciate you for providing screen shots of the issue. Can you also provide the following for me please:

- Link to your account
- Link to the page where the issue is happening 
- A screenshot of your console log for possible errors (Chrome -> Right click -> Inspect -> Console Tab)

Regards,
Carlo Argel

**Comment by sydholl** [comment]
WandB Internal User commented: 
Carlo-Argel commented: 
HI @xiaowen0110 ,

I just want to follow up if you still need more assistance with this.

Regards,
Carlo Argel

**Comment by Carlo-Argel** [comment]
Hi @xiaowen0110 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
