### ISSUE TITLE
[CLI 0.16.0] an artifact download creates a run

### ISSUE THREAD

**Issue by yellowhat** [wandb/wandb#6604]
### Describe the bug

Hi,
updating from 0.15.12 to 0.16.0 I noticed that everytime we download a model from the registry a new run is created.

This is particularly annoying if you download the model in CI.

```python
api = wandb.Api()
artifact = api.artifact(MODEL)
path = artifact.download()
```

From the documentation I cannot find a way to disable this behaviour.

Thanks

### Environment

WandB version: 0.16.0

OS: Linux

Python version: 3.10

Versions of relevant libraries:

**Comment by thanos-wandb** [comment]
Hi @yellowhat thank you for reporting this issue. I've reproduced the same behavior in wandb `v0.16.0` where a new run with job type `auto` will be created. I have raised this matter with our engineers in Artifacts/Models team and will keep you posted here on any updates.

**Comment by thanos-wandb** [comment]
Hi @yellowhat I wanted to follow up on this issue, and let you know that this is expected behavior and introduced in v0.16.0 This was required to support [Nexus](https://github.com/wandb/wandb/tree/main/nexus). We will get rid of the run when the SDK supports using Nexus without a run, most likely in the next release. You may downgrade to v0.15.12 for now if that causes any issues with your CI/CD pipelines. I will go ahead and close this ticket now, but feel free to reopen this if you had any more questions or issues.
