### ISSUE TITLE
[CLI]: `wandb login` and/or `wandb init` are broken

### ISSUE THREAD

**Issue by dominiquegarmier** [wandb/wandb#6647]
### Describe the bug

```shell
wandb login --relogin  # insert api key
wandb init

Let's setup this directory for W&B!
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
Your login information seems to be invalid: can you log in again please?
We're sorry, there was a problem logging you in. Please send us a note at support@wandb.com and tell us how this happened.
```

### Environment

WandB version: `wandb==0.16.0`

OS: MacOS `14.1.1`

Python version: `3.10.11`

### Additional Context

I suspect that `wandb login` does actually do anything, since `wandb.init(...)` is also broken in python.

**Comment by umakrishnaswamy** [comment]
hey @dominiquegarmier - few questions & troubleshooting suggestions:

- what entity are you using to log in? are you doing this via a personal account or a service account?
- what happens when you try to log in in a fresh environment?
- could you try running `rm ~/.netrc` in your CLI & then running `wandb login --relogin` ?

thank you!

**Comment by umakrishnaswamy** [comment]
hey @dominiquegarmier - few more troubleshooting suggestions/questions:

- export WANDB_BASE_URL=https://api.wandb.ai before relogging in 
- calling wandb login --relogin --host=https://api.wandb.ai 
- are you running this behind any sort of proxy? any details about your networking setup would be super helpful here

apologies again for the inconvenience!

**Comment by dominiquegarmier** [comment]
doing step (2) worked, thanks for the help.
