### ISSUE TITLE
[Q] How can I overwrite logs when using PyTorchLightning and wandb?

### ISSUE THREAD

**Issue by QinlongHuang** [wandb/wandb#6717]
I'm a PL + wandb user, and I load my checkpoint using
```python
# checkpoint format:
# 'exp/h31qedvw/checkpoints/model-01841-val_loss=0.31116.ckpt'
wandb_id = args.checkpoint.split('/')[1]
logger = WandbLogger(project='wav2lip-syncnet', id=wandb_id, resume='must')
trainer = pl.Trainer(max_steps=hparams.nsteps, 
                    devices=1, accelerator="gpu", 
                    logger=logger, log_every_n_steps=1, 
                    callbacks=[checkpoint_callback])
trainer.fit(model, ckpt_path=args.checkpoint)
```
It seems ok on resume training, and I have manually modified some hparams like `lr`. Note that I have break my last run on epoch 1900, while I load a ckpt on epoch 1841, cuz I save ckpt with top-k metrics. When I watch my logs on `wandb`, it seems the I cannot overwrite the previous logs from 1841-1900. Is there anyway to do that?

**Comment by Carlo-Argel** [comment]
Hi @QinlongHuang ,

Thank you for reaching out. Let me double-check this.

**Comment by Carlo-Argel** [comment]
Hi @QinlongHuang ,

To resume runs and update historical steps using WandB, you can follow these steps:
1. Automatic Resuming:
   - If your script did not exit successfully and you want to resume the run automatically, you can pass resume=True to wandb.init(). This will allow W&B to automatically resume the run from the last logged step when you restart the script.
   - Ensure that you are running your script in the same directory as the one that failed because W&B stores the resume file (wandb/wandb-resume.json) in the local directory.
2. Controlled Resuming with a Run ID:
   - If you want more control over the resuming process, you can use a unique run_id for each run. You can generate a run_id using wandb.util.generate_id() and pass it to wandb.init(id=run_id, resume="allow"). This will allow W&B to resume the run with that specific ID.
   - If you want to ensure that the run must be resumed and not create a new run if the specified run does not exist, you can use resume="must" instead of resume="allow".
3. Resuming with wandb.restore:
   - Use wandb.restore to load checkpoint files that you have saved during your run. This will not automatically restore the state of your code, so you need to ensure that your code is set up to load these checkpoints and resume from the correct state.
   - Use wandb.save to create checkpoint files during your run. These files can then be restored using wandb.restore when you resume the run.
4. Logging Additional Metrics After Resuming:
   - After resuming a run, you can continue to log additional metrics using wandb.log or update the summary with wandb.summary. This will add new data to the historical steps of the run.Here's an example of how you might resume a run and log additional metrics:
python
import wandb

# Generate a unique run ID or use a previously generated one
run_id = "your-unique-run-id"

# Initialize a W&B run with resuming enabled
wandb.init(project="your-project-name", id=run_id, resume="allow")

# Your code to load the model and optimizer state, if applicable
# ...

# Continue training or evaluation
for epoch in range(start_epoch, n_epochs):
    # Your training or evaluation loop
    # ...

    # Log metrics
    wandb.log({"metric_name": metric_value}, step=epoch)

# Finish the run
wandb.finish()
Remember to replace "your-unique-run-id" and "your-project-name" with your actual run ID and project name. The start_epoch should be set to the epoch where you want to resume your training or evaluation.If you're resuming a run that was part of a sweep or a more complex workflow, make sure to handle the resuming logic accordingly, as resuming runs from sweeps is not supported directly.

**Comment by Carlo-Argel** [comment]
Hi @QinlongHuang ,

- Wandb step must be monotonically increasing in each call, otherwise the step value is ignored during your call to log().
- Currently wandb does not support overwriting historical steps
- Our recommendation in this case is to create a new run and log new data in it for the continued training. You can additionally add a group name to these runs to keep track of them in your workspace as being related to each other. 
- We will log a feature request for this, please let me know how this impacts your workflow and why this is important to you
