### ISSUE TITLE
[Q] No config record after "wandb sync <...>" 

### ISSUE THREAD

**Issue by Hmartin1978** [wandb/wandb#6754]
Thanks for your greak works!
I found that I always get **_Network error_** when the training was done, but maybe this one isn't such a tricky problem? Because I can **_sync_** the training log manually, but the problem is there is no config record in the wandb web(I know the config can be found in folder, but I want to record it in the web). So could you give me some advice to solve it?
![1](https://github.com/wandb/wandb/assets/115940971/32549f44-1709-42ac-a88e-7289034fc548)

**Comment by rsanandres-wandb** [comment]
Hello @Hmartin1978 !

There can be two issues here that causes this: the Network Error is causing the config to malformed or the config you are logging is appearing somewhere else.

To confirm could you provide me the following:
- The stack trace of the Network Errors at the end of your runs
- A code snippet of how you are logging your config within your run
- What `wandb` SDK version you are using

**Comment by rsanandres-wandb** [comment]
There is a possibility the config file is not being saved since we expect to save it during `finish()`. Could you try to run in [offline mode](https://docs.wandb.ai/guides/technical-faq/setup#can-i-run-wandb-offline) moving forward and then syncing them to `wandb` after? This will ensure that wandb will save all the correct files and will save your config for you. As for your current runs, you can [update the config ](https://docs.wandb.ai/guides/integrations/add-wandb-to-any-library#updating-the-wandb-config)even after the run is finished in case you want to add the configs back.
