### ISSUE TITLE
LlamaIndex integration error  

### ISSUE THREAD

**Issue by jramnara** [wandb/wandb#6773]
### Describe the bug

I attempted integration as suggested here - https://docs.llamaindex.ai/en/stable/module_guides/observability/observability.html

```python
from llama_index import set_global_handler

set_global_handler("wandb", run_args={"project": "llamaindex"})

```

But, receive the following error 
```
Failed to log trace tree to W&B: 'CompletionUsage' object has no attribute 'get'
```

### Environment

WandB version:

OS:

Python version:

Versions of relevant libraries:

### Additional Context

Running my llamaindex python program on colab.

**Comment by rsanandres-wandb** [comment]
Hello @jramnara !

```
from llama_index import set_global_handler
import wandb
import llama_index

print(wandb.__version__)
print(llama_index.__version__)


set_global_handler("wandb", run_args={"project": "llamaindex"})
```

This worked for me with `wandb==0.16.1` and `llama_index==0.9.22`. Could you try installing these versions of the packages

**Comment by jramnara** [comment]
Thank you, @rsanandres-wandb . 
I have the same versions for the packages. The tracing fails when I use the OpenAIAgent in LlamaIndex. 
```python
tool = QueryEngineTool.from_defaults(query_engine=query_engine)
agent = OpenAIAgent.from_tools([tool], llm=llm, system_prompt=agent_context, verbose=True, memory=memory)
agent.chat("..... ") ## this is where I see the 'failed to log trace' message

```

**Comment by rsanandres-wandb** [comment]
Got it! I would recommend looking at this [report](https://wandb.ai/ayush-thakur/llama-index-report/reports/Building-Advanced-Query-Engine-and-Evaluation-with-LlamaIndex-and-W-B--Vmlldzo0OTIzMjMy) for more information on this but this discrepancy is likely due to our OpenAI integration not being integrated for `openai>=1.0.0` at the time which has since been updated. You can see[ this example ](https://github.com/wandb/weave/blob/master/examples/experimental/openai_monitoring.ipynb)notebook to help see the updates.

**Comment by ayulockin** [comment]
Hey @jramnara, W&B Trace is an old product offering which is not maintained anymore. We were focused on shipping a better tooling called W&B Weave. Team is working on the LlamaIndex integration.

[Weave announcement](https://wandb.ai/wandb/weave-announcement/reports/Weave-Simple-tools-for-applying-Generative-AI--Vmlldzo3NDE0Mjcx)
[Weave Documentation](https://wandb.github.io/weave/)

Closing this issue for now. Do let me know if you need anything more.
