### ISSUE TITLE
[Q] Create a similar chart to the gradient one

### ISSUE THREAD

**Issue by ColdFrenzy** [wandb/wandb#6914]
Hi all,
I want to create a chart representing the variation of a distribution over time. Something that is equivalent to the gradient chart of a network when using wandb.watch over that network. Do you have any suggestions on how to do it?

**Comment by ColdFrenzy** [comment]
Hi @fmamberti-wandb thank you for your answer. Actually, if I try to use this method, it actually logs nothing, I'm not sure why.
```
train_metrics["train_metrics/strategy_duration"] =  wandb.Histogram(np.array([value/sum(strategy_duration.values()) for _, value in strategy_duration.items()]))
```
That's part of the metric that I log, but doing so, there is no chart called "strategy_duration" on wandb

**Comment by fmamberti-wandb** [comment]
Hi @ColdFrenzy, how are you logging `train_metrics["train_metrics/strategy_duration"]` ?

for the Histogram to be plotted as shown above, every time a step is logged (so every time you run `wandb.log()`)  you should pass the array with the distribution for one step to `wandb.Histogram()`, rather than a list of arrays with all the distributions.

**Comment by fmamberti-wandb** [comment]
Hi @ColdFrenzy , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ColdFrenzy** [comment]
Sorry for the super late reply, the problem was described here:

https://github.com/wandb/wandb/issues/1211#issuecomment-993504902

So, the histogram is there, but I was not able to see it from the project page
