### ISSUE TITLE
[Feature]: Add Direct Command Agent For Launch Just like the agent in sweeps doing.

### ISSUE THREAD

**Issue by steven12138** [wandb/wandb#7060]
### Description

I recently encountered challenges while working with the mm-segmentation library, which necessitated running pip install -v -e . to install the source code as a development Python package. Consequently, explaining how to configure the Python environment in the Dockerfile proved complex. Additionally, I lack sudo access, preventing me from installing Docker on my server.

Currently, I'm utilizing sweeps to search for hyperparameters. I've observed that the agent in sweeps merely requires specifying the start command in the sweeps configuration file, which suits my situation well.

Is there a way to create a Queue with features like Launch, enabling me to use different hyperparameters to sequentially launch experiments? This would eliminate the need to wait and manually initiate the next experiment in some ablation studies.

### Suggested Solution

I'd like the "Launch" feature to seamlessly utilize the existing Python environment and execute experiments sequentially,  configuring the start command within a specific location, enabling the use of different hyperparameters for each experiment. Furthermore, I want the flexibility to either specify which agent to run this process with or allow WandB to automatically select the most suitable option.

### Additional Context

If there is a feature already available that meets my requirements, please let me know. Thank you very much! 😃

**Comment by steven12138** [comment]
I attempted to use `Prefect` for this task, but I found it challenging to use and it necessitated a Python script, rather than allowing for configuration directly through the Web UI.

**Comment by fmamberti-wandb** [comment]
Hi @steven12138, thank you for reaching out with your question. When you mention:

> enabling me to use different hyperparameters to sequentially launch experiments

Are you trying to run sequential experiments testing different values for a number of hyperparameters, but rather than using one of the Sweep search methods, you would like to be able to select for each iteration of the experiment the values manually and have these running in a sequential manner?

**Comment by steven12138** [comment]
Yeah, it's kind of that
Even more I just want the launch can use the similar settings as the sweeps function.
That means i can queue the difference experiment (even different code)

**Comment by fmamberti-wandb** [comment]
Hi @steven12138, as mentioned in our [documentation](https://docs.wandb.ai/guides/launch#how-it-works) Launch is a product designed to scale training runs to remote resources rather than running them locally. I will report your feedback to our engineering team about having the chance to launch jobs locally without having to use Docker for environments like yours where can't be installed.

My recommendation in your case would be:

- Create the sweeps for each of the hyperparameter searches you have to run
- Create the training function for each of the sweep
- Have a script that loops through the sweeps id starting the sweeps for each task sequentially 

I'd be happy to setup an example and provide the required code if needed.

**Comment by fmamberti-wandb** [comment]
Hi @steven12138, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by steven12138** [comment]
> Hi @steven12138, as mentioned in our [documentation](https://docs.wandb.ai/guides/launch#how-it-works) Launch is a product designed to scale training runs to remote resources rather than running them locally. I will report your feedback to our engineering team about having the chance to launch jobs locally without having to use Docker for environments like yours where can't be installed.
> 
> My recommendation in your case would be:
> 
>     * Create the sweeps for each of the hyperparameter searches you have to run
> 
>     * Create the training function for each of the sweep
> 
>     * Have a script that loops through the sweeps id starting the sweeps for each task sequentially
> 
> 
> I'd be happy to setup an example and provide the required code if needed.

Genius! I really hadn't thought of that approach. Thank you so much for your help!

**Comment by fmamberti-wandb** [comment]
You are welcome 😄 - I will mark this as solved now but feel free to reach out in the future if you have any further questions or feedback!
