### ISSUE TITLE
[App]: When using the GUI, plots created by wandb.plot.line_series() cannot be inspected with the cursor (i.e. when hovering over the graph with the cursor, nothing happens)

### ISSUE THREAD

**Issue by assafbk** [wandb/wandb#7138]
### Current Behavior

When using the GUI, plots created by wandb.plot.line_series() cannot be inspected with the cursor (i.e. when hovering over the graph with the cursor, nothing happens)

### Expected Behavior

A pop-up window should open showing the value at the location of the cursor, along with the name of the graph (like in regular plots)

### Steps To Reproduce

1. create a multiline plot:
wandb.log({"some_id" : wandb.plot.line_series(
                       xs=[0,1,2,3,4], 
                       ys=[[0,1,2,3,4],[0,1,2,3,4]],
                       keys=["graph_a", "graph_b"],
                       title="example",
                       xname="x axis")})
2. go to the GUI and hover with the cursor over the graph
3. see that nothing happens

### Screenshots

bad behvior:
![image](https://github.com/wandb/wandb/assets/38749017/4979a699-4186-4a13-b71f-9dc22dc11164)

normal behavior (regular plot):
![image](https://github.com/wandb/wandb/assets/38749017/eb0390d2-10b7-42c8-b723-5aa614f63b47)

### Environment

OS: ubuntu 16.04

Browsers: chrome

Version: 107.0.5304.110

**Comment by fmamberti-wandb** [comment]
Hi @assafbk - thank you for reaching out. This is expected behaviour with the Lineseries custom chart preset created using `wandb.plot.line_series`

You could create a new preset that also includes a tooltip from the Lineseries preset, changing line 21 to:
```
"mark": {"type": "line", "tooltip": {"content": "data"},"interpolate": "linear"},
```

You can also find more info on how to use Custom Charts presets on our [docs](https://docs.wandb.ai/guides/app/features/custom-charts/walkthrough#docusaurus_skipToContent_fallback).

Please let me know if you have any further questions on this.

**Comment by assafbk** [comment]
Thanks!
