### ISSUE TITLE
[App]: Lineage for dataset crashes

### ISSUE THREAD

**Issue by maximefuchs** [wandb/wandb#7195]
### Current Behavior

After adding a dataset reference to an old run using:
```python
# resume run to add dataset
run = wandb.init(id=id_run, project=project, resume="must")
# add dataset reference
artifact = wandb.Artifact(name=name_dataset, type="dataset")
# Add dataset directory to artifact
artifact.add_reference(f"file://{path_to_dataset}", max_objects=3000000)  
run.log_artifact(artifact)
run.finish()
```
The dataset is correctly uploaded, but when I want to see the Lineage of the artefact I stumble on "an error occurred":
![Screenshot from 2024-03-21 09-48-18](https://github.com/wandb/wandb/assets/47177763/7faee6ce-1a9f-4021-8d9b-df02d3e772e5)

### Environment

OS: Linux Ubuntu 22.04.4 LTS

Browsers: Chrome 122.0.6261.128

wandb 0.16.4

**Comment by estellazx** [comment]
Hi @maximefuchs I found the faulty artifact lineage, looks like your lineage probably looks something like this?
`dataset(in a project that has been deleted) -> run -> new dataset`
Thats whats causing the crash we are trying to look at the lineage that contains a deleted project. Will put in a fix to not crash page, thanks for reporting.

**Comment by estellazx** [comment]
This is an older run, I'm thinking you might have `use_artifact` in the past for this run, and that artifact you used the project of that artifact is now deleted. 

If you go click into the run of this broken lineage artifact, on the left side bar click artifacts. You will see all the input and output artifacts on this page. You should see an input artifact and if you click into that artifact you should see that it gives a 404 error since that project is deleted.

**Comment by estellazx** [comment]
There is a lag for an artifact being deleted after a project has been deleted so its in a weird place right now where the artifact still shows up some places but will be deleted in a few days

**Comment by ArtsiomWB** [comment]
Hey guys! tagging myself on this thread for tracking purposes.
