### ISSUE TITLE
[CLI]: WARNING: No AMD GPUs specified

### ISSUE THREAD

**Issue by collinmccarthy** [wandb/wandb#7319]
### Describe the bug

On a server managed by Slurm, which has both NVIDIA and AMD GPUs installed, if we only request NVIDIA GPUs we get `WARNING: No AMD GPUs specified` flooding the console. I commented in #6757 but didn't get a response so I'm opening a new issue since that one is closed.

### Environment

```console
$ conda list | grep wandb
wandb                     0.16.6                   pypi_0    pypi

$ conda list | grep python
python                    3.11.8          hab00c5b_0_cpython    conda-forge

$ lsb_release -a
Description:    Ubuntu 22.04.4 LTS
```

### Additional Context

```console
$ rocm-smi -a --json
WARNING: No AMD GPUs specified
{"system": {"Driver version": "6.3.6"}}

$ cat /sys/module/amdgpu/initstate
live
```

**Comment by kptkin** [comment]
@collinmccarthy sorry that you still experience this issue, we are currently in the process of replacing our amd  system metric with a roc-smi tool (we were using the installed binary to extract the relevant information), hopefully it should be fixed in the next release. In the short-term, we will review our original fix and try to make sure that this warning is suppress.

**Comment by kptkin** [comment]
@collinmccarthy the only way is to mess with your installed code, if you want to do it you can just short-circuit our check for amd, here: https://github.com/wandb/wandb/blob/main/wandb/sdk/internal/system/assets/gpu_amd.py#L167
but we are actually fixing it now and should be releasing it soon

**Comment by collinmccarthy** [comment]
Awesome, I see the PR. If it gets blocked I’ll edit the code you linked, otherwise I’ll just wait. Thank you so much!
