### ISSUE TITLE
[Q] Can't create a team after deleting one in an org

### ISSUE THREAD

**Issue by t-sekai** [wandb/wandb#7565]
Hi, 

I first created a corporate team. Realizing it has a trial period, I deleted the team, but the org is still there. Then, I changed the corporate org to an academic org; but now when I try to create a new team, the button isn't pressable. I'm not sure what I'm doing wrong. My profile link is: https://wandb.ai/tsc003

**Comment by anmolmann** [comment]
Hey @t-sekai , are you able to see the Teams panel on the bottom left in the UI like this:

![image](https://github.com/wandb/wandb/assets/20401632/dfb43aec-02f5-4cb6-b606-274a34aafd2f)

Upon clicking `Create a team to collaborate`, you should be able to see a modal pop up on the right hand side in the UI:
![image](https://github.com/wandb/wandb/assets/20401632/5e21721d-7828-4977-af55-fb6623b7f9be)

Upon filling in the team details, you should be able to create a team. If this is not the case for you, could you please create a screen recording of what issue you are facing and send it our way so that we can further investigate into the issue?

**Comment by t-sekai** [comment]
I've tried the steps above, but the "Create team" button is unclickable before and after I enter the team name.

<img width="1671" alt="Screen Shot 2024-05-06 at 11 44 56 PM" src="https://github.com/wandb/wandb/assets/110834590/f101de74-678e-4003-9450-5049070684f2">

**Comment by anmolmann** [comment]
Hey @t-sekai , apologies for the confusion. If you are a part of an academic org (and a team in that org) already, you cannot create a new team in another academic org. I've relayed this discrepancy to our product team as well and out team will be updating the messaging in the UI shortly to reflect the same.

**Comment by t-sekai** [comment]
I understand the problem now. Can you help me delete the hm_gesture-org from my account? It's no longer useful.

**Comment by anmolmann** [comment]
Hey @t-sekai , `hm_gesture-org` is now deleted.
