### ISSUE TITLE
[Q] How to rename the specific logged metrics in the whole projects. 

### ISSUE THREAD

**Issue by StaminaTang** [wandb/wandb#7700]
Hello!
Thank you for your excellent work!

I am writing to ask for the help of changing the name of specific logged metrics of the whole project. For example, previously, I logged the reward as "environment" in project A using algorithm A, however, I have to move/copy all of the runs to another project B to compare with algorithms B. Although the metric has the same meaning, it has different names in A ("environment") and project B (eval/rewards). If I could not change the metric name, I could not make the comparison in the same plot.
<img width="261" alt="image" src="https://github.com/wandb/wandb/assets/17592448/fef05012-8f7d-475c-b692-bc2464aa8e76">

Is there any way to change the logged metric name? I have already known the usage of config update and group name change, but I have no idea of changing the metric name. Could you please give me a suggestion to solve this problem?

Thank you very much!

**Comment by paulosabile-wb** [comment]
Hi @StaminaTang 

Good day and thank you for reaching out to us. Happy to help you on this! We really appreciate your feedback with using our platform.

Upon checking, there is an [option ](https://docs.wandb.ai/guides/track/public-api-guide#rename-a-metric-in-a-run-after-the-run-has-finished)to rename a metric column but currently this only applies to tables. Charts will still refer to metrics by their original names.

Let me check for a while if there are other options we can try and I will get back to you. Otherwise, if this feature does not exist then I can only think of logging the metrics again with the updated name. Please give me some time to review this.


Best Regards,
Paulo

**Comment by gsaltintas** [comment]
If the comparison is done only on Wandb, one simple alternative could be to plot both of those metrics in the plots. In your workspace edit the plot, add both metric names to the corresponding axis under the Data tab

**Comment by paulosabile-wb** [comment]
Thank you @gsaltintas! Hi @StaminaTang would the workaround above work for you?

**Comment by paulosabile-wb** [comment]
Hi @StaminaTang Since we have completed the request, we will now mark this as Solved. Please feel free to reach out again if you need assistance!

Have a great day ahead!


Best Regards,
Paulo

**Comment by wabbajack1** [comment]
@gsaltintas what about if the x-axis is different in the naming. Since both x-axis are the same but the naming is different, I cant plot them together.
