### ISSUE TITLE
[App]: Request to increase rate limit and missing runs from dashboard

### ISSUE THREAD

**Issue by ayushnoori** [wandb/wandb#7883]
Resharing from my [post](https://community.wandb.ai/t/request-to-increase-rate-limit-and-missing-runs-from-dashboard/7056) on the W&B form in case this is a bug in the web app.

> I’m training several models concurrently and am encountering the following error:
>
> ```
> wandb: 429 encountered (Filestream rate limit exceeded, retrying in 2.1 seconds.), retrying request
> ```
>
> May I kindly request to increase my user rate limit?
>
> Also, I noticed that on our compute cluster, I am running 8 jobs (e.g., checked via squeue), but only six runs appear active in the W&B dashboard. For example, I identified a job, with run name 00:56:03 on 06/30/2024 (29437), that produces logs that confirm that the job is running. The SLURM job ID is 38009820, and I can use squeue to confirm that the job is actively running with runtime 16:31:20. However, I don’t see this run on my W&B dashboard. May you please advise how to resolve this issue?

### Environment

OS: Rocky Linux release 8.9 (Green Obsidian)

Browsers: Chrome, Edge

Version: 0.17.2

**Comment by JasonArkens17** [comment]
Dear ayushnoori,

Thank you for reaching out with your queries, and I appreciate your understanding as we work through these challenges together.

Regarding your request to increase your user rate limit, I'm sorry to inform you that we are currently unable to adjust individual rate limits due to our infrastructure and fairness policies. However, I can suggest a few strategies that might help you manage and work within the existing limits:

1. **Implement Timeouts and Retries:** You're already observing automatic retries when the rate limit is exceeded. To further smooth this process, consider implementing additional timeouts and controlled retries in your code. This can help manage the flow of requests and reduce the frequency of hitting rate limits.

2. **Stagger Your Requests:** If possible, try staggering the start times of your model training jobs or introduce a slight delay between consecutive API calls. This approach can distribute the load more evenly over time and reduce peak demand on the API.

3. **Optimize Data Logging:** Review the data you are logging and reduce the frequency or volume where feasible. For example, you might choose to log only key metrics or summaries rather than detailed data at every step.

Regarding the discrepancy you've noticed on the W&B dashboard where some runs are not appearing, this issue may be related to network or configuration settings that delay or prevent the synchronization of data to the dashboard. Here are a few steps to troubleshoot and potentially resolve this issue:

- **Check Network Configuration:** Ensure that there are no network restrictions or configurations that might block or limit outbound connections from your compute cluster to the W&B servers.
  
- **Verify Integration and Settings:** Double-check the integration setup and configuration for each job to ensure they are correctly set up to log data to W&B.

- **Review Logs for Errors:** It might be helpful to review the logs from the missing runs to see if there are any errors or warnings related to data logging or network issues.

If these steps do not resolve the problem, please share the log files from one of the affected runs, and we will take a closer look to provide further assistance.

Thank you for your cooperation and understanding. We are committed to supporting you and ensuring your experience with W&B is as productive as possible. Please do not hesitate to reach out if you have any more questions or need further assistance.

Best,
Jason
