### ISSUE TITLE
[Q] Log structured data into wandb.Table

### ISSUE THREAD

**Issue by woowho** [wandb/wandb#7913]
Hi,

I am seeking help on avoiding duplicating entries in wandb.Table.

I am currently using wandb to log the per-episode stats for an RL project. I have multiple environments running concurrently for some indeterminate number of steps so they are not guaranteed to generate output at every logging time step. At the conclusion of each episode, some structured data is generated which I hope to log into wandb as a table so that I can generate visualizations after the fact.

I am currently maintainding a pd dataframe to log all data generated since the start of training and log the entire table to wandb on every update. This proves to be quite in efficient.

My question is: are there any ways I can treat the table as a write only database and have the same table persist throughout the training process so that I only need to give it incremental updates?

Thanks!

**Comment by vitoria-wandb** [comment]
Hey @woowho !

Could you show you a snippet of your code to show us how you are logging your table and metrics?

What you could do instead is to simply log your metrics without a table and have in the workspace a custom chart where you can visualize your data in a tabular way as it gets logged. 

Let us know if this is what you meant, 

Thanks, 
Vitoria

**Comment by woowho** [comment]
Hi thanks for the reply!

The logging code is kinda complicated since there is a bunch of multiprocessing happening. The general gist is that the same RL agent runs in multiple environments simultaneously. At every time step, these environments are advanced at the same time. After the step, some criteria are checked about whether these environments are terminated, and if they are, some metrics would be logged. Consequently, at the same timestep, there could be no datapoints, one datapoint, or many datapoints being logged.

The core of the issue is that given my setup, using global step as the index is not sufficient. The datapoints are only unique if indexed by both global step and an environment id. I could log these datapoint separately, but ideally they are interchangeable and should not be viewed as separate datapoints (i.e. instead of multiple line plots, a scatter plot would be more appropriate). This is why I am not sure if logging the data directly would work.

There are not too many entires during each training (less than 10k entries). If I could log them into a continuously updated table without rewriting, it would be sufficient.

Thanks!

**Comment by vitoria-wandb** [comment]
Hey @woowho 

Thank you so much for your reply and for your patience with this!

I have a couple of questions/clarifications to ask and to provide:

- when you say `step`, are you referring to [step](https://en.wikipedia.org/wiki/Reinforcement_learning) in a reinforcement learning context?
- I ask the above, because I am concerned to confuse that with the wandb concept of step. In wandb, everytime you call the function `wandb.log()` , it automatically logs a new [step](https://docs.wandb.ai/ref/python/log#docusaurus_skipToContent_fallback), so I want to make sure I understand to which step in which context you are referring to

From my understanding though, overall, for your use case, it seems that what could help you would be to have:
- a single table with columns N , i.e. with N features (metrics) and rows M, but you are adding a row at every update (I will call it update, but I assume it is your RL-step here) 
- a row is added at each update/iteration, and you want to keep 1 single table where at the end you will have M rows (not new columns, still same amount of columns N)
- and you want to be able to see this same column over time, and ideally before the training run is over
- {please confirm this} and you are running all of this in 1 single wandb run, correct? Please let me know if that is not the case.


We have another customer with a similar workflow and I am currently working on a possible code demo/solution and suggestion for this, but I would like you to confirm to me if:
- scenario a: it is the case for you to be running a single wandb run , writing to the same table
- scenario b: or multiple wandb runs (in multiple separate processes, a process per wandb run) writing to the same table 
- as the implementation suggestion would differ. 

Thank you for your continued patience with this, let me know, thanks!
