### ISSUE TITLE
CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)[App]: 

### ISSUE THREAD

**Issue by Ibrah-N** [wandb/wandb#7959]
### Environment

OS:

Browsers:

Version:

**Comment by JoanaMarieL** [comment]
Hi @Ibrah-N , thank you for writing in and happy to help. Could you please share a code snippet when you received this error message? Thanks!

**Comment by Ibrah-N** [comment]
@JoanaMarieL  Thanks it been solved by the wandb team as they replied.

**Comment by Ibrah-N** [comment]
@JoanaMarieL 
Here is the code that cause the error
![Screenshot (34)](https://github.com/user-attachments/assets/9b0d35c0-0c3f-4b04-ad9a-0bb615b8f953)

**Comment by JoanaMarieL** [comment]
> @JoanaMarieL Thanks it been solved by the wandb team as they replied.

Glad to hear that is resolved now, but I would like to confirm if you have further questions? Thanks~ thanks for providing the code you have.

**Comment by JoanaMarieL** [comment]
Hi @Ibrah-N , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by Ibrah-N** [comment]
@JoanaMarieL  Thanks for letting me know. I'll check today again and will inform accordingly.

**Comment by JoanaMarieL** [comment]
Following up if you have further question :) @Ibrah-N

**Comment by Ibrah-N** [comment]
@JoanaMarieL 
Thanks it been solved now.

**Comment by tortolla** [comment]
Have the same problem: I have logged in successfully, but I am getting error: wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)

**Comment by tortolla** [comment]
Now I am getting this problem: ---------------------------------------------------------------------------
CommError                                 Traceback (most recent call last)
Cell In[4], line 17
     14         print(e)
     16 # Инициализация W&B
---> 17 wandb.init(project="flops_calculation", entity="ivanov-fed")
     21 # Функция для создания модели
     22 def create_model():

File ~/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py:1191, in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, fork_from, resume_from, settings)
   1187     logger.exception("error in wandb.init()", exc_info=e)
   1189 # Need to build delay into this sentry capture because our exit hooks
   1190 # mess with sentry's ability to send out errors before the program ends.
-> 1191 wandb._sentry.reraise(e)
   1192 raise AssertionError()

File ~/.local/lib/python3.10/site-packages/wandb/analytics/sentry.py:155, in Sentry.reraise(self, exc)
    152 self.exception(exc)
    153 # this will messily add this "reraise" function to the stack trace,
    154 # but hopefully it's not too bad
--> 155 raise exc.with_traceback(sys.exc_info()[2])

File ~/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py:1177, in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, fork_from, resume_from, settings)
   1175     wi = _WandbInit()
   1176     wi.setup(kwargs)
-> 1177     return wi.init()
   1179 except KeyboardInterrupt as e:
   1180     if logger is not None:

File ~/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py:781, in _WandbInit.init(self)
    779         backend.cleanup()
    780         self.teardown()
--> 781     raise error
    783 assert run_result is not None  # for mypy
    785 if not run_result.HasField("run"):

CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process - I am working on server and I am already logged in(tried relogging and it didn't help)

**Comment by JoanaMarieL** [comment]
Hi @tortolla , can you tell us more about your experiment so we could understand better and provide the following:

- Code Snippet
- the debug.log and debug-internal.log. These files are under your local folder wandb/run-<date>_<time>-<run-id>/logs in the same directory where you’re running your code.

**Comment by JoanaMarieL** [comment]
Hello @tortolla  , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
