### ISSUE TITLE
[Q]Why cannot log older step metrics?

### ISSUE THREAD

**Issue by ericxsun** [wandb/wandb#7967]
In wandb/sdk/internal/handler.py, logging metrics with a step value less than an existing step will fail, meaning we cannot log metrics for an older step.

https://github.com/wandb/wandb/blob/a93ad79990a9129ced605005e69134e588082573/wandb/sdk/internal/handler.py#L577
<img width="985" alt="image" src="https://github.com/user-attachments/assets/13326dbe-4819-4dc4-bb08-a1189fb41f46">

However, in many cases, we evaluate our trained model using various metrics from an earlier stage. For example, we might update new metrics and re-evaluate using an older checkpoint.

Should we make it looks like this:
```
        if step is not None:
            if step < self._step:
                self._flush_partial_history()
                self._step = step
            elif step > self._step:
                self._flush_partial_history()
                self._step = step
```

Or is there another solution that would allow us to log metrics for an older step?

**Comment by luisbergua** [comment]
Hey @ericxsun! I think you could find [rewind](https://docs.wandb.ai/guides/runs/rewind) and [fork](https://docs.wandb.ai/guides/runs/forking) runs helpful for your use case. Mind letting me know if that's the case and we can enable these features for you?

**Comment by tristanengst** [comment]
I've dealt with this a lot—my solution is far from perfect but achieves what I need. The key idea is to separate the **order** of when something was logged from its **place in training**, eg. checkpoint. You can resume your run and then update values by logging something like
```
wandb.log(dict(previous_checkpoint_index=1, value_to_update=2), step=next_step_in_training)
```
The main disadvantages are that it messes with logged system information, runtime, and your plots can be default look very wrong, owing to the added number of steps. I also don't think this can handle images or other media that can't have a customized x-axis.

Fixing these issues would be in my opinion be the greatest possible improvement to WandB.

**Comment by kptkin** [comment]
@ericxsun the reason we have to drop is due to the way the data is stored in our backend, which requires the `_step` values to be monotonically increasing, if we send these values out of order this could have unexpected consequences. 

@tristanengst we hear you and we agree that this is experience should be improved and we are working on plans how to fix it, but it is quite a fundamental change in our system, so it take us some time to land on the optimal solution.

In the meantime, i wonder if something like our [`define_metric`](https://docs.wandb.ai/guides/track/log/customize-logging-axes#customize-axes) could help in some of your cases.

Also could you describe your use-cases:
1. Do you need the step values only for plotting against an alternative x-axis?
2. Or do you need something like what @luisbergua shared where you would like to resume from an arbitrary step?

Thanks for your valuable inputs, we are always happy to hear from our users :)

**Comment by ericxsun** [comment]
The [define_metric](https://docs.wandb.ai/guides/track/log/customize-logging-axes#customize-axes) seems to involve a trade-off, and I’ve used a same way before. It requires changing the x-axis, which is set to `step` by default in the UI.
 
In practice, I need to evaluate different model checkpoints at known training steps and log the evaluation metrics sequentially from step 1 to step N. Occasionally, I need to re-evaluate a checkpoint at an intermediate step (1 < X < N) and log the results.

Therefore, I would prefer if wandb could log information for older steps as well.

**Comment by luisbergua** [comment]
Hey @ericxsun! Could you please share your username so we can enable our new features [rewind](https://docs.wandb.ai/guides/runs/rewind) and [fork](https://docs.wandb.ai/guides/runs/forking) for you?

**Comment by ericxsun** [comment]
> Hey @ericxsun! Could you please share your username so we can enable our new features [rewind](https://docs.wandb.ai/guides/runs/rewind) and [fork](https://docs.wandb.ai/guides/runs/forking) for you?

@luisbergua  Thank you very much. My wandb usename is qinluo.

**Comment by luisbergua** [comment]
Hey @ericxsun! We enabled those features for your account

**Comment by ericxsun** [comment]
> Hey @ericxsun! We enabled those features for your account

Wow, Thanks so much @luisbergua . I'll try.
