### ISSUE TITLE
Wandb Table being Logged Multiple Times

### ISSUE THREAD

**Issue by EdIzaguirre** [wandb/wandb#7969]
### Describe the bug

I am noticing that my Wandb table is being logged twice, sometimes three times when running my code inside of Metaflow. I suspect that there may be some strange interaction between Metaflow and Wandb that may be causing this issue. Or perhaps I am not understanding how the table logging is to be done? One bit of complexity to note is that I am starting a run in one step, and then resuming it in the next step. I have confirmed via print statements that the logging of the table is only done once. Any help would be appreciated, thank you!

```python
@step
    def augment_data_train_model(self):
       ...
        # Start a run, tracking hyperparameters
        run = wandb.init(
            project=os.getenv('WANDB_PROJECT'),
            entity=os.getenv('WANDB_ENTITY'),
            config=self.config
        )

        config = wandb.config
        self.run_id = run.id

        ....

        run.finish()

        self.next(self.evaluate_model)

@step
    def evaluate_model(self):
        run = wandb.init(
            project=os.getenv('WANDB_PROJECT'),
            entity=os.getenv('WANDB_ENTITY'),
            config=self.config,
            id=self.run_id,
            resume="allow"
        )

        config = wandb.config

        class_set = wandb.Classes([
            {'name': name, 'id': id} for id, name in class_mapping.items()
        ])

        # Setup a WandB Table object to hold our dataset
        table = wandb.Table(
            columns=["Ground Truth", "Predictions"]
        )

        for example in val_dataset.take(config.num_examples):
           ....

                predicted_image = wandb.Image(
                    image,
                    classes=class_set,
                    boxes={
                        "ground_truth": {
                            "box_data": all_boxes,
                            "class_labels": class_mapping,
                        }
                    }
                )

            table.add_data(ground_truth_image, predicted_image)
        print("Logging table.")
        wandb.log({"Plant Disease Predictions": table})
        run.finish()
```

```shell

```

### Environment

WandB version:
wandb==0.17.3

OS:
macOS 14.5 Sonoma

Python version:
Python 3.11.9

Versions of relevant libraries:
metaflow==2.12

**Comment by paulosabile-wb** [comment]
Hi @EdIzaguirre Good day and thank you for reaching out to us. Happy to help you on this!

By default, tables cannot log data incrementally and I assume this is the reason why the tables are logged separately, but I need to review this further. Additionally, I am not sure what will be the expected behavior if we are resuming runs so I'll check this. I haven't seen this behavior in the past.

When you said the tables are logged multiple times, do they have the same data in your workspace or they contain different contents? E.g. Step 1 - Table 1 was logged with image1, Step 2 - Table 2 was logged with image 2 and Table 1 still has image 1?

Can you describe how the tables looks like if they are logged multiple times using your code snippet? Do you have a workspace/project URL where we can find these tables that you are referring to so we can review and investigate what might be happening?

I am looking forward for your next update.


Best Regards,
Paulo

**Comment by EdIzaguirre** [comment]
Hi Paulo,

- Ah I didn't know that tables couldn't log data incrementally. I thought that if I used `table.add_data` multiple times this was fine, but and that `wandb.log()` table should only be done once.
- The same data is logged multiple times, they are identical copies of the table.
- [Here is a link](https://wandb.ai/ed-izaguirre/plant-object-detection/runs/8nmly3te?nw=nwuseredizaguirre) to my workspace so you can take a look. Here is an image:
<img width="1845" alt="Screenshot 2024-07-18 at 7 17 06 AM" src="https://github.com/user-attachments/assets/996ca1da-82cc-4401-bccf-2f463c3656ea">

**Comment by paulosabile-wb** [comment]
Hi @EdIzaguirre The table should be logged only once but here's a sample [code snippet](https://github.com/wandb/examples/blob/master/colabs/tables/Log_Tables_Incrementally.ipynb) that might help you how to log data incrementally to a table. Let me know if this helps!

**Comment by paulosabile-wb** [comment]
Hi @EdIzaguirre we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
