### ISSUE TITLE
[CLI]: Multiple sweeps at the same time / project not recognized the sweep id

### ISSUE THREAD

**Issue by JuliusLhamo** [wandb/wandb#8077]
### Sweep does not recognize new project

I have multiple python scripts with wandb sweeps integrated, my lstm_sweep works fine, but when I adjust my code for my gru script it still automatically changes to my lstm_sweep even though I adjusted the wandb.init() wandb.sweep() etc.. Below I share some code snippet

```python
def train_and_evaluate(config=None):
    with wandb.init(config=config, name= 'gru_sweep', project='bt_jimtradeops_gru') as run:
        print(f"Running in project: {run.project}, entity: {run.entity}")
        config = wandb.config 

# ...

for key in data_dict.keys():
    data = data_dict[key]
    wandb.login(key='d40849de664f2d44875582f9a3467c486aa76bc3')
    sweep_id = wandb.sweep(gru_sweep_config, project='bt_jimtradeops_gru', entity='jimskitchen')
    print(f"Running sweep with ID: {sweep_id}")
    wandb.agent(sweep_id, train_and_evaluate, count=1) 
```

I get this output  but if you see the project it is adding the runs to it is the lstm one not the gru! 

```shell
weep URL: https://wandb.ai/xxx/bt_jimtradeops_lstm/sweeps/9h90mvet
wandb: Agent Starting Run: x29ulade with config:
wandb:  batch_size: 64
wandb:  hidden_size: 256
wandb:  learning_rate: 0.00019300678321570175
wandb:  num_layers: 4
wandb:  seq_length: 2
wandb: Currently logged in as: user123 (xyz). Use `wandb login --relogin` to force relogin
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: Tracking run with wandb version 0.17.5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lstm_sweep
wandb: ⭐️ View project at https://wandb.ai/xyz/bt_jimtradeops_lstm
wandb: 🧹 View sweep at https://wandb.ai/xyz/bt_jimtradeops_lstm/sweeps/9h90mvet
wandb: 🚀 View run at https://wandb.ai/xyz/bt_jimtradeops_lstm/runs/x29ulade
```

My wandb settings are like this:
```shell
wandb status --settings
```
with this output 
```shell
{
  "_extra_http_headers": null,
  "_proxies": null,
  "api_key": null,
  "base_url": "https://api.wandb.ai",
  "entity": null,
  "git_remote": "origin",
  "ignore_globs": [],
  "project": null,
  "root_dir": null,
  "section": "default"
}
```
so maybe i can enforce this behaviour to track the gru project by adjusting the settings

I 

### Environment

WandB version:  0.17.5

OS: Linux-5.15.0-113-generic-x86_64-with-glibc2.35

Python version: 3.11.9

Versions of relevant libraries:

**Comment by JasonArkens17** [comment]
Thank you for providing those details about the issue you're experiencing with your W&B sweeps. There are a few things we can try to resolve this:

1. First, let's check if there are any environment variables set that could be overriding your project settings:

```
echo $WANDB_PROJECT
echo $WANDB_ENTITY
```

If these are set, they may be taking precedence over what you specify in your code.

2. In your sweep configuration, make sure you've explicitly set the project:

```python
gru_sweep_config = {
    ...
    'project': 'bt_jimtradeops_gru',
    ...
}
```

3. When initializing the sweep, try specifying both the project and entity:

```python
sweep_id = wandb.sweep(gru_sweep_config, project='bt_jimtradeops_gru', entity='jimskitchen')
```

4. In your `train_and_evaluate` function, remove the `project` argument from `wandb.init()` since it's being ignored in sweeps. Instead, set it in the sweep configuration:

```python
def train_and_evaluate(config=None):
    with wandb.init(config=config, name='gru_sweep') as run:
        ...
```

5. You can also try setting the project and entity in your settings file. Create a file named `.wandb` in your home directory with the following content:

```yaml
[default]
project = bt_jimtradeops_gru
entity = jimskitchen
```

6. If none of the above work, you can try forcing the project in your code right after the wandb.init() call:

```python
def train_and_evaluate(config=None):
    with wandb.init(config=config, name='gru_sweep') as run:
        run.project = 'bt_jimtradeops_gru'
        ...
```

7. Lastly, make sure you're not accidentally reusing a sweep ID from your LSTM project. Always create a new sweep for each distinct configuration.

Could you try these steps and let me know if any of them resolve the issue? Also, it would be helpful to see the full sweep configuration (`gru_sweep_config`) to ensure everything is set correctly there.
