### ISSUE TITLE
[Q] Why there is a sentry-sdk dependency (privacy/security concern)?

### ISSUE THREAD

**Issue by omerfarukabaci** [wandb/wandb#8130]
Hello, first of all thanks for creating and maintaning this package.

I was wondering that why this package is [dependent to sentry-sdk](https://github.com/wandb/wandb/blob/main/pyproject.toml#L18). There is also a [default DSN](https://github.com/wandb/wandb/blob/main/wandb/analytics/sentry.py#L28) defined. We have some privacy concerns about what is Sentry being used for and how. As you may appreciate we don't want any of our data to end up in your Sentry, knowingly or unknowingly.

Thanks for your help in advance!

**Comment by kptkin** [comment]
@omerfarukabaci thanks for writing in. 

We use Sentry only for analytical purposes to capture errors that happen with our library in order to see potential errors that happen to our users and fix it for them. 

No user data should be captured as part of this as it only capture a stack trace of our library's code. 

Since we are open source you could see all instance of this usage in our code by searching for `wandb._sentry.reraise` or `wandb._sentry.exception` where we capture an exception and/or re-raise it to send to sentry.

if you still would like to disable this, you could set the following environment variable  `WANDB_ERROR_REPORTING` to `false`.

Hope it helps!

**Comment by omerfarukabaci** [comment]
Thank you for your answer @kptkin!

> No user data should be captured as part of this as it only capture a stack trace of our library's code.

I wonder how you make sure that the stack trace only includes `wandb` library's code? Assume that I am calling `wandb.init()` within my source code, which calls `wandb._sentry.reraise` in case of an exception. The stack trace of the exception will include the source code that is calling `wandb.init()`. Am I missing something here?

> if you still would like to disable this, you could set the following environment variable WANDB_ERROR_REPORTING to false.

Thanks for the suggestion, but I would assume this to be `False` by default.

**Comment by kptkin** [comment]
@omerfarukabaci 
Theoretically it is possible (although we truncate the output), but so far we never observed. 
Thanks for your input, this is a valid suggestion, we will discuss internally and update the repository in case we decide to change our defaults.

Closing issue as resolved. Please don't hesitate to reach out with further questions.

**Comment by omerfarukabaci** [comment]
Thank you for your consideration @kptkin!
