### ISSUE TITLE
[Bug]: Typing issue wandb.Api(): Api not callable

### ISSUE THREAD

**Issue by rogerwelo** [wandb/wandb#8520]
### Describe the bug

It looks like version 0.18.2 introduces a typing problem, which is not present in 0.18.1.
Example (as per [documentation](https://docs.wandb.ai/guides/track/public-api-guide/#export-run-data)): 
```
import wandb
api = wandb.Api()
```
 mypy message:  `error: "Api" not callable`

wandb version: 0.18.2
mypy version: 1.11.2
python version: 3.11.9

**Comment by rogerwelo** [comment]
Hi!
Sorry, that was just a typo in my comment here. The issue still persists.

**Comment by bdvllrs** [comment]
I have the same issue. 
The versions and code reported by @rogerwelo is enough to reproduce this:

wandb version: 0.18.2
mypy version: 1.11.2
python version: 3.11.9

And:
```python
import wandb
api = wandb.Api()
```

git bisect shows that the commit that introduced the regression is: ed8518a55b48b0f8601e143eccca3960dd165e0c.

The error is in the `wandb/__init__.py` stub file which types:
```python
Api: PublicApi
```
instead of 
```python
Api: type[PublicApi]
```

I'm writing a PR to fix it.

**Comment by alexb5903** [comment]
Just installed it and cannot enter anything at the 
       ..hit enter, or press ctrl+c to quit:
prompt
