### ISSUE TITLE
[Bug-App]: Missing options for grouped plots

### ISSUE THREAD

**Issue by zzbuzzard** [wandb/wandb#8707]
### Describe the bug

The "Grouping" window for my grouped plots is, for some reason, limited to just a few options:
![Image](https://github.com/user-attachments/assets/7cc3b16f-0f41-486c-9440-9273327b0f01)

so I am unable to, for example, set the range to be Std Dev, or select Median aggregation. This is quite annoying, and it used to work fine within this project, so I'm not sure what has changed.  The plot shown is a group of five runs, all of which definitely logged to this plot and are currently set to visible. I tried changing the legend to use `${stddev}` as listed in the docs, but it just shows up as an empty string. What's going on here?

OS: Windows 10
Browser: Chrome Version 130.0.6723.59

Edit: in fact, the options are missing for every plot in this project after grouping

**Comment by ArtsiomWB** [comment]
Hi @zzbuzzard! Thank you for writing in!

What are you grouping your runs by in order to reproduce this behavior? Are you seeing this behavior in the grouped workspace of the run, or are you seeing this in the project's workspace?

**Comment by zzbuzzard** [comment]
Hi @ArtsiomWB, sorry for the slow reply. I am grouping them by a config item, but I've just checked and grouping by e.g. State produces the same result. This is in the project workspace.

**Comment by ArtsiomWB** [comment]
Hi @zzbuzzard, no worries! looks like you are running into this behavior because of the `full fidelity` mode on your chart. I see a similar behavior until I change my chart to `random sampling` (video attached)
https://github.com/user-attachments/assets/a718e797-e4bf-4b9c-8d33-8a54b313447b

If you are interested in changing all of the charts on your workspace to `random sampling` at once, you can do it by going to the workspace settings and into the `line plots` tab, and turning on `random sampling` under the `Point aggregation method` settings. 
https://github.com/user-attachments/assets/301f6418-2393-4f63-9004-27500842b131

**Comment by zzbuzzard** [comment]
@ArtsiomWB wow, what! Thanks so much, that totally fixed it (and thanks for the video too).

FWIW this seems a bit counterintuitive to me, and I don't think I would've ever arrived at this solution alone; perhaps there should be a tip in the Grouping window when Full fidelity is enabled that says "options are limited in full fidelity mode" or something? Also, I don't know how I turned on full fidelity mode, but as I had a small number of data points the limitation shouldn't really have mattered.

Anyway, thanks again. My issue is fixed so I will close, but I do think the UI around this somewhat subtle point could be improved, so consider this a feature request now rather than a bug :)
